Translate Leaf to Japanese
vapor/docs pull request #1005
Opened 2024-09-01 07:58 UTC by KaitoMuraoka

[Leaf content](https://docs.vapor.codes/ja/leaf/overview/) translated into Japanese

- getting-started.md
- overview.md
- custom-tags.md

2024-09-01 11:57 UTC, lemo-nade-room requested changes

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/getting-started.ja.md
> +JavaScript や CSS ファイルを提供する予定がある場合は、Vapor の [`FileMiddleware`](https://api.vapor.codes/vapor/documentation/vapor/filemiddleware) を有効にして、 `/Public` フォルダからファイルを提供できるようにすることをお勧めします。
（どちらでも構わないですが )
英語の方で、提供することも可能ですとありますが、おすすめとは書いていないように感じました。

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/getting-started.ja.md
> +    もし、コードエディタとして VSCode を使用している場合、シンタックスハイライトを有効にするために、Leaf 拡張機能をインストールすることをお勧めします：Leaf HTML](https://marketplace.visualstudio.com/items?itemName=Francisco.html-leaf)
`Leave HTML]`となっていて、`[`が抜けていました。

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/getting-started.ja.md
> +これにより、Leaf を直接呼び出すのではなく、`Request` の汎用 `view` プロパティを使用します。これにより、テスト時に別のレンダラーに切り替えることができます。
`これにより`がこの一文で2回使用されていますが、1つ目の`これにより`は`ここでは、`などの方が正しいと思われます。

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/overview.ja.md
> +Leaf は、Swift 風の構文を持つ強力なテンプレート言語です。これを使って、フロントエンドのウェブサイト用に動的な HTML ページを生成したり、API から送信するリッチなメールを生成したりすることができます。
どちらでもいいのですが、getting-startedと同様の訳し方でSwiftにインスパイアされたの方が個人的にはかっこよくて好きです。

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/overview.ja.md
> +- 名前 `coun` : タグを識別するための名前です
`coun`がタイポです。`count`です

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/overview.ja.md
> +- ボディ：一部のタグには、コロンと閉じタグを使用して任意の body を提供できます
若干日本語的に意味が掴みにくかったので
`コロンと閉じタグを使用して任意のボディを追加できるタグもあります`
などどうでしょうか

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/overview.ja.md
> +これらの4つの要素は、タグの実装に応じて様々な使い方ができます。 Leaf のビルドインタグがどのように使われるか、いくつかの例をみてみましょう。
`これらの4つの要素は、タグの実装に応じて様々な使い方ができます。`
の訳し方綺麗だなと思いました。

好みになりますが、`ビルドインタグ`がわかりづらかったので`標準タグ`とかどうでしょうか

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/overview.ja.md
> +Leaf は、Swift でお馴染みの多くの式もサポートしています。
👍

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/overview.ja.md
> +[Getting Started](getting-started.ja.md) の例では、 `[String: String]` 辞書を使って Leaf にデータを渡しましたが、`Encodable` に準拠する任意のデータを渡すことができます。実際、`[String: Any]` はサポートされていないため、`Encodable` な構造体を使用する方が推奨されます。つまり、配列を直接渡すこ
👍

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/overview.ja.md
> +`#contains` タグは、配列と値を2つのパラメータとして受け取り、パラメータ1の配列にパラメータ2の値が含まれているかどうかを返します。
👍

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +	もしカスタムタグが HTML をレンダリングする場合は、HTML がエスケープされないように、`UnsafeUnescapedLeafTag` に準拠させる必要があります。ユーザー入力のチェックやサニタイズを忘れないようにしましょう。
👍

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +`NowTag` を実装したので、Leaf にそれを伝えるだけです。このようにして、別のパッケージから来るタグでも追加することができます。通常、これを `configure.swift` で行います：
好みですが
`別のパッケージから来るタグでも`の代わりに`たとえ別のパッケージで定義されたタグだったとしても`の方がより綺麗だと思いました。

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +The `LeafContext` contains two important properties. `parameters` and `data` that has everything we should need.
元の英文も混ざっちゃっています

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +`LeafContext` には、重要なプロパティが 2 つあります。それが `parameters` と `data` です。この 2 つで必要な情報はすべて揃っています。
👍

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +### サンプルの Hello タグ
`Helloタグによる実例`とかの方がしっくりくる気がします。英語そのままでもいいかもです

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +これを理解するために、両方のプロパティを使ったシンプルな hello タグを実装してみましょう。
👍

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +最初のパラメータに名前が含まれていることを想定しています。
少しニュアンスが違うような気がしました。

直訳で`名前を含む最初のパラメータにアクセスできます。`
整えると`nameの値が提供される、1つ目のパラメータにアクセスできます`
な気がします

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +データプロパティの中の "name" キーを使って名前の値にアクセスします。
dataがプロパティ名なのでそのまま`data`と英語表記の方がわかりやすいかもです

2024-09-01 11:57 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +#### パラメータの使用
parametersがプロパティ名なのでそのままparametersと英語表記の方がわかりやすいかもです

2024-09-01 12:57 UTC, KaitoMuraoka commented on docs/leaf/getting-started.ja.md
> +    Xcode から実行する際に Leaf がテンプレートを見つけられるようにするためには、 Xcode ワークスペースの [custom working directory](../getting-started/xcode.md#custom-working-directory) を設定する必要があります。
リンクがずれている場合、原文を修正した方が良いともうのですが、どうでしょうか？

https://github.com/vapor/docs/blob/b6846b8ac25f6957e1d50ae24d70537f4d86643b/docs/leaf/getting-started.md?plain=1#L48C116-L48C168

2024-09-01 13:09 UTC, KaitoMuraoka commented on docs/leaf/getting-started.ja.md
> +JavaScript や CSS ファイルを提供する予定がある場合は、Vapor の [`FileMiddleware`](https://api.vapor.codes/vapor/documentation/vapor/filemiddleware) を有効にして、 `/Public` フォルダからファイルを提供できるようにすることをお勧めします。
「フォルダからファイルを提供できるようにすることも可能です。」に変更します

2024-09-01 13:19 UTC, KaitoMuraoka commented on docs/leaf/custom-tags.ja.md
> +`NowTag` を実装したので、Leaf にそれを伝えるだけです。このようにして、別のパッケージから来るタグでも追加することができます。通常、これを `configure.swift` で行います：
「だった」は話し言葉な気がするので、「たとえ別のパッケージで定義されたタグでも追加することができます。」の方が文章としては自然だと思うのですが、いかがでしょうか？

2024-09-01 13:29 UTC, KaitoMuraoka commented
@lemo-nade-room 
I fixed docs and replied to your comment.

2024-09-01 13:45 UTC, lemo-nade-room commented on docs/leaf/getting-started.ja.md
> +    Xcode から実行する際に Leaf がテンプレートを見つけられるようにするためには、 Xcode ワークスペースの [custom working directory](../getting-started/xcode.md#custom-working-directory) を設定する必要があります。
あ、いえ、日本語に飛ぼうとするのですが、見出しを日本語で書いちゃうとidに反映されなくてURLが変わってしまうので原文は大丈夫だと思います

```
# Custom Working Directory // → id="custom-working-directory"が属性としてつくため大丈夫
```

```
# カスタムワーキングディレクトリ // → idが連番で id="_1"がついてしまうのでURLが変わる
```

このリンクの方を合わせるか、日本語時の見出しを英語にするかにすると合うと思います！

2024-09-01 13:47 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
> +`NowTag` を実装したので、Leaf にそれを伝えるだけです。このようにして、別のパッケージから来るタグでも追加することができます。通常、これを `configure.swift` で行います：
ありがとうございます！ とてもいいと思います！

2024-09-01 13:49 UTC, lemo-nade-room commented on docs/leaf/custom-tags.ja.md
>  #### データの使用
こちらもdataの方がいいかと思われます！

2024-09-04 01:21 UTC, KaitoMuraoka commented on docs/leaf/custom-tags.ja.md
>  #### データの使用
DONE! : https://github.com/vapor/docs/pull/1005/commits/820ab002a52f0adb0c21cf5ed3bfcd333e61b485

2024-09-04 02:15 UTC, lemo-nade-room commented on docs/leaf/getting-started.ja.md
> +    Xcode から実行する際に Leaf がテンプレートを見つけられるようにするためには、 Xcode ワークスペースの [custom working directory](../getting-started/xcode.md#custom-working-directory) を設定する必要があります。
@KaitoMuraoka  こちら確認していただきたいです！

2024-09-05 07:15 UTC, KaitoMuraoka commented on docs/leaf/getting-started.ja.md
> +    Xcode から実行する際に Leaf がテンプレートを見つけられるようにするためには、 Xcode ワークスペースの [custom working directory](../getting-started/xcode.md#custom-working-directory) を設定する必要があります。
修正しました！：https://github.com/vapor/docs/pull/1005/commits/674c164cc90f4559ac6b21666e845bc256023386

2024-09-06 05:45 UTC, lemo-nade-room approved these changes
I approved this Pull request.

2024-09-06 16:08 UTC, 0xTim commented
@KaitoMuraoka thanks for this! There's one broken link in the new page - as soon as that's fixed we can merge. Are you able to take a look?

2024-09-09 05:54 UTC, KaitoMuraoka commented
@0xTim 
Fix DONE! 🚀

2024-09-09 05:56 UTC, KaitoMuraoka commented on docs/leaf/getting-started.ja.md
> +    Xcode から実行する際に Leaf がテンプレートを見つけられるようにするためには、 Xcode ワークスペースの [custom working directory](../getting-started/xcode.md#custom-working-directory) を設定する必要があります。
.md は必要みたいでした
https://github.com/vapor/docs/pull/1005#issuecomment-2334385169

`../getting-started/xcode.md/#_1`

2024-09-09 05:59 UTC, lemo-nade-room commented on docs/leaf/getting-started.ja.md
> +    Xcode から実行する際に Leaf がテンプレートを見つけられるようにするためには、 Xcode ワークスペースの [custom working directory](../getting-started/xcode.md#custom-working-directory) を設定する必要があります。
すみません、ありがとうございます

2024-09-09 09:47 UTC, 0xTim approved these changes

2024-09-09 09:47 UTC, merged