Improved the queues.md page to add a little extra info about testing, and update the fluent community driver
vapor/docs pull request #1008
Opened 2024-10-22 14:46 UTC by Dracks

* Updated the fluent community driver to the new version in vapor-community.
* Added a small brief of the asyncDriver to allow people know you can use that for testing

2024-10-22 17:50 UTC, gwynne requested changes

2024-10-22 17:50 UTC, gwynne commented on docs/advanced/queues.md
> +- [QueuesFluentDriver](https://github.com/vapor-community/vapor-queues-fluent-driver)
On second thought, I don't think this should be updated until I've made a non-beta release of the updated version, which hasn't happened yet.

2024-10-22 17:57 UTC, Dracks commented on docs/advanced/queues.md
> +- [QueuesFluentDriver](https://github.com/vapor-community/vapor-queues-fluent-driver)
ok! then what is your recomendation? close the P/R? revert this?

2024-10-22 18:14 UTC, gwynne requested changes
Added a couple of grammatical and spelling suggestions

2024-10-22 18:14 UTC, gwynne commented on docs/advanced/queues.md
> +To avoid syncronization problems and get a deterministic testing, the Queues package provides an XCTQueue library and an AsyncTestQueuesDriver driver dedicated to testing. that you can use as follows
Grammar and spelling nits:
```suggestion
To avoid synchronization problems and ensure deterministic testing, the Queues package provides an `XCTQueue` library and an `AsyncTestQueuesDriver` driver dedicated to testing which you can use as follows:
```

2024-10-22 18:14 UTC, gwynne commented on docs/advanced/queues.md
> +See more in the Blog post from [Romain puclet](https://romain.codes/2024/10/08/using-and-testing-vapor-queues/)
Grammar and spelling nits:
```suggestion
See more details in [Romain Pouclet's blog post](https://romain.codes/2024/10/08/using-and-testing-vapor-queues/).
```

2024-10-22 18:49 UTC, gwynne approved these changes
LGTM, thanks for adding this!

2024-10-22 18:51 UTC, Dracks commented
I changed the title, to drop the update of the driver

2024-11-03 22:50 UTC, 0xTim approved these changes
Thanks!

2024-11-03 22:59 UTC, merged