feat(validation.md): added custom validator documentation
vapor/docs pull request #1016
Opened 2024-12-04 11:39 UTC by WilliamFernsV3

I created a [PR](https://github.com/vapor/vapor/pull/3263) earlier today, adding in a custom validator called `Custom`. This allows users to easily create custom validations, it is simpler to use and shorter in syntax compared to the current [Custom Validators](https://docs.vapor.codes/basics/validation/#custom-validators).

2024-12-04 11:42 UTC, WilliamFernsV3 reviewed
Good overall.

2024-12-04 11:42 UTC, WilliamFernsV3 commented on docs/basics/validation.md
> +      "nameAndSurname",
Looks great overall.

2024-12-07 07:24 UTC, WilliamFernsV3 commented
@0xTim here is a PR I made for the custom validator PR in the core repository. Feel free to merge this once the other one gets merged. 

Thanks :)

2024-12-07 07:29 UTC, WilliamFernsV3 commented
This PR also fixes this issue: https://github.com/vapor/docs/issues/1015

2024-12-07 14:55 UTC, WilliamFernsV3 commented
I think this is a small improvement in the documentation. Should we keep it or not?

Link: https://docs.vapor.codes/basics/validation/

Before:
Vapor's Validation API helps you validate incoming request before using the [Content](https://docs.vapor.codes/basics/content/) API to decode data.

After:
Vapor's Validation API helps you validate the body and query parameters of an incoming request before using the [Content](content.md) API to decode data.

2024-12-20 18:49 UTC, 0xTim requested changes
One change otherwise LGTM! Thanks!

2024-12-20 18:49 UTC, 0xTim commented on docs/basics/validation.md
> +More information on `.custom` validator at [[#Custom Validators]].
Lets keep the first one as well (so have both sentences)

2024-12-20 19:51 UTC, WilliamFernsV3 commented on docs/basics/validation.md
> +More information on `.custom` validator at [[#Custom Validators]].
Sure.

2024-12-20 19:56 UTC, WilliamFernsV3 commented on docs/basics/validation.md
> +More information on `.custom` validator at [[#Custom Validators]].
Done. Let me know if there is anything else.

2024-12-30 19:00 UTC, 0xTim approved these changes

2025-01-01 17:15 UTC, merged