Add Spanish translation for security/passwords.md
vapor/docs pull request #1027
Opened 2024-12-10 10:01 UTC by alemohamad

Add Spanish translation for security/passwords.md

2024-12-10 22:29 UTC, TheHandyOwl requested changes

2024-12-10 22:29 UTC, TheHandyOwl commented on docs/security/passwords.es.md
> +Password hashing algorithms are designed to be slow and CPU intensive. Because of this, you may want to avoid blocking the event loop while hashing passwords. Vapor provides an asynchronous password
Delete this paragraph

2024-12-10 22:37 UTC, TheHandyOwl commented on docs/security/passwords.es.md
> +
```suggestion

```

2024-12-11 06:58 UTC, jacostaf10 approved these changes
LGTM, ready to go!

2024-12-11 09:22 UTC, merged