Adds tracing documentation
vapor/docs pull request #1039
Opened 2024-12-22 20:43 UTC by NeedleInAJayStack

Adds new Tracing chapter to document API introduced in https://github.com/vapor/vapor/pull/3253

2024-12-22 21:05 UTC, slashmo commented on docs/basics/tracing.md
> +            withSpan("process", context: span) { _ in
```suggestion
            withSpan("process", context: span.context) { _ in
```

2024-12-23 04:39 UTC, NeedleInAJayStack commented on docs/basics/tracing.md
> +            withSpan("process", context: span) { _ in
Ah, good catch! I've fixed it. Thanks!

2024-12-23 15:43 UTC, 0xTim requested changes
Couple of comments and need to move the location

2024-12-27 00:22 UTC, NeedleInAJayStack reviewed
Thanks for the review! I think I've addressed all the comments.

2024-12-27 00:22 UTC, NeedleInAJayStack commented on docs/basics/tracing.md
> +To automatically create a fully annotated span for each request, add the `TracingMiddleware` to your application.
Good idea. Done!

2024-12-27 00:22 UTC, NeedleInAJayStack commented on docs/basics/tracing.md
I've moved it to the advanced section.

2024-12-27 09:55 UTC, slashmo commented on docs/advanced/tracing.md
> +To ensure that tracing identifiers are passed along correctly, this should be added before any middleware that calls tracing APIs or connects to external services.
I'd go a step further and say that `TracingMiddleware` should be as early as possible in the chain, because the sooner this is invoked the more honest is the duration of the span in relation to actual response time.

2024-12-28 19:25 UTC, NeedleInAJayStack commented on docs/advanced/tracing.md
> +To ensure that tracing identifiers are passed along correctly, this should be added before any middleware that calls tracing APIs or connects to external services.
Great point. I've adjusted it to say that it should be added as early as possible.

2024-12-30 17:22 UTC, 0xTim approved these changes
Thanks!

2024-12-30 17:29 UTC, merged