Created transaction documentation
vapor/docs pull request #548
Opened 2020-09-28 10:01 UTC by Craz1k0ek

Added documentation for the transaction syntax, based on the 3.0 documentation and current implementation.
Added the Star model as example model, as it is used throughout the Fluent examples.

2020-09-29 17:21 UTC, Craz1k0ek commented
Possibly fixes [this issue](https://github.com/vapor/docs/issues/531)

2020-10-01 10:14 UTC, 0xTim requested changes
Great start! Just a few nits to resolve

2020-10-01 10:14 UTC, 0xTim commented on 4.0/docs/fluent/transaction.md
> +This is usually an incoming HTTP request. Use the `req.db.transaction(_ closure:)` method.
Nit formatting and tighten up the language
```suggestion
To perform a transcation, you need access to something that can connect to the database. This is usually an incoming HTTP request. For this, use `req.db.transaction(_ :)`:
```

2020-10-01 10:14 UTC, 0xTim commented on 4.0/docs/fluent/transaction.md
> +The closure expects an `EventLoopFuture<T>` return value. Once this future completes succesfully, the transaction will be commited.
Nit remove
```suggestion
Once this closure returns successfully, the transaction will be committed.
```

2020-10-01 10:14 UTC, 0xTim commented on 4.0/docs/fluent/transaction.md
> +Once the transaction is completed, the result can be transformed to, for example, a simple HTTP status response to indicate completion as shown below.
Nit remove passive voice
```suggestion
Once the transaction completes, the result can be transformed into a different future, for example into a HTTP status to indicate completion as shown below:
```

2020-10-01 10:14 UTC, 0xTim commented on 4.0/docs/fluent/transaction.md
> +return req.db.transaction { (database) -> EventLoopFuture<Void> in
Nit - match the style guide

```suggestion
return req.db.transaction { database in
```

2020-10-01 10:14 UTC, 0xTim commented on 4.0/docs/fluent/transaction.md
> +return req.db.transaction { (database) -> EventLoopFuture<Void> in
Nit match the style guide
```suggestion
return req.db.transaction { database in
```

2020-10-01 10:14 UTC, 0xTim commented on 4.0/docs/fluent/transaction.md
> +req.db.transaction { (database) -> EventLoopFuture<Void> in
Nit match style guide

```suggestion
req.db.transaction { database in
```

2020-10-01 10:14 UTC, 0xTim commented on 4.0/docs/fluent/transaction.md
> +Once inside the transaction closure, you must use the supplied database (named `database` in the example) to perform queries.
Clarify where the database comes from
```suggestion
Once inside the transaction closure, you must use the database supplied in the closure parameter (named `database` in the example) to perform queries.
```

2020-10-01 11:29 UTC, 0xTim approved these changes
Thanks!

2020-10-01 11:29 UTC, merged