OTP documentation
vapor/docs pull request #558
Opened 2020-10-07 09:41 UTC by Craz1k0ek

* Added OTP documentation

2020-10-07 19:08 UTC, tanner0101 reviewed
This looks great, thank you!

2020-10-07 19:08 UTC, tanner0101 commented on 4.0/docs/crypto.md
> +```swift
A brief description of what HOTP is (and maybe how it differs from TOTP?) could be helpful here before the code snippet.

2020-10-07 19:08 UTC, tanner0101 commented on 4.0/docs/crypto.md
> +```swift
Same here.

2020-10-07 20:04 UTC, grundoon commented on 4.0/docs/crypto.md
> +A TOTP is an addition to the HOTP. It works the same, but it uses time instead of a counter to generate uniqueness. Due to latency problems, both networks but also humans related, the TOTP is generat
> Due to latency problems, both networks but also humans related, the TOTP is generated over a time interval.

This feels a bit clunky to me – perhaps something along the lines of:

To compensate for minor skews introduced by unsynchronized clocks, network latency and user delay, a TOTP is generated to be valid over a specified time interval.

2020-10-07 21:19 UTC, tanner0101 approved these changes

2020-10-07 21:19 UTC, tanner0101 commented on 4.0/docs/crypto.md
> +A TOTP is an addition to the HOTP. It works the same, but it uses time instead of a counter to generate uniqueness. Due to latency problems, both networks but also humans related, the TOTP is generat
👍

2020-10-08 17:13 UTC, grundoon approved these changes
👍 Thanks for adding these!

2020-10-16 10:47 UTC, gwynne requested changes
Excellent documentation - I love the inclusion of the conceptual background especially! My only concerns are the result of my usual grammatical perfectionism, the content itself is great 🙂.

2020-10-16 10:47 UTC, gwynne commented on 4.0/docs/crypto.md
> +Vapor supports both HOTP and TOTP one-time passwords. The OTP's work with the SHA-1, SHA-256 and SHA-512 hash functions and can provide six, seven or eight digits of output. An OTP is able to provide
- In the second sentence, replace `The OTP's` with `OTPs` - there is more than one OTP (plural, not possessive), and the article is erroneously specific in this context.
- In the second sentence, add a comma immediately after `SHA-256` (Oxford comma).
- Also add a comma immediately after `seven` (Oxford comma).
- Suggest rephrasing the third sentence as "An OTP provides authentication by generating a single-use human-readable password." (active voice, simplified phrasing)
- Suggest removing the parenthesis on the fourth sentence and adding clarification, e.g. `"... agree on a symmetric key, which must be kept private at all times to maintain the security of the generated passwords." (high-importance subclause, emphasis on security requirement)

The resulting paragraph would be:
```suggestion
Vapor supports both HOTP and TOTP one-time passwords. OTPs work with the SHA-1, SHA-256, and SHA-512 hash functions and can provide six, seven, or eight digits of output. An OTP provides authentication by generating a single-use human-readable password. To do so, parties first agree on a symmetric key, which must be kept private at all times to maintain the security of the generated passwords.
```

2020-10-16 10:47 UTC, gwynne commented on 4.0/docs/crypto.md
> +The HOTP is an OTP based on HMAC's. In addition to the symmetric key, both parties also agree on a counter, which is a number, providing uniqueness for the password. After each generation attempt, th
- Remove "The" (excessive use of article)
- Replace `HMAC's` with `an HMAC digest` (plural, not possessive, and use a more descriptive phrasing).
- Remove the comma between "number" and "providing" (unnecessary subclause division).
Result:
```suggestion
HOTP is an OTP based on an HMAC digest. In addition to the symmetric key, both parties also agree on a counter, which is a number providing uniqueness for the password. After each generation attempt, the counter is increased.
```

2020-10-16 10:47 UTC, gwynne commented on 4.0/docs/crypto.md
> +A TOTP is an addition to the HOTP. It works the same, but it uses time instead of a counter to generate uniqueness. To compensate for minor skews introduced by unsynchronized clocks, network latency
Suggest rephrasing the entire paragraph:
```suggestion
A TOTP is a time-based variation of the HOTP. It works mostly the same, but instead of a simple counter, the current time is used to generate uniqueness. To compensate for the inevitable skew introduced by unsynchronized clocks, network latency, user delay, and other confounding factors, a generated TOTP code remains valid over a specified time interval (most commonly, 30 seconds).
```

2020-10-16 10:47 UTC, gwynne commented on 4.0/docs/crypto.md
> +OTP's are very useful for giving some leeway in validation and out of sync counters. Both OTP implementations have the ability to generate the OTP for an error margin.
- Replace `OTP's` with `OTPs` (possessive -> plural)
- Replace `giving some` with `providing` (phrasing)
- Replace "the OTP for an error margin" with "an OTP with a margin for error" (phrasing)
Result:
```suggestion
OTPs are very useful for providing leeway in validation and out of sync counters. Both OTP implementations have the ability to generate an OTP with a margin for error.
```

2020-10-16 10:47 UTC, gwynne commented on 4.0/docs/crypto.md
> +The example above allows for a margin of 2, which means the HOTP will be calculated for the counter value `23 ... 27` and all of these codes will be returned.
- Replace `value` with `values` (more than one)
- Add a comma after the range (run-on clause)
```suggestion
The example above allows for a margin of 2, which means the HOTP will be calculated for the counter values `23 ... 27`, and all of these codes will be returned. 
```

2020-10-16 10:47 UTC, gwynne commented on 4.0/docs/crypto.md
> +    Note: giving a higher margin will reduce the security as an attacker has more time or freedom to perform attacks.
Rephrase:
```suggestion
    Note: The larger the error margin used, the more time and freedom an attacker has to act, decreasing the security of the algorithm.
```

2020-10-16 11:34 UTC, Craz1k0ek commented on 4.0/docs/crypto.md
> +The HOTP is an OTP based on HMAC's. In addition to the symmetric key, both parties also agree on a counter, which is a number, providing uniqueness for the password. After each generation attempt, th
Omit the word digest, HMAC is not a digest algorithm, but a MAC algorithm.

2020-10-16 12:17 UTC, gwynne commented on 4.0/docs/crypto.md
> +The HOTP is an OTP based on HMAC's. In addition to the symmetric key, both parties also agree on a counter, which is a number, providing uniqueness for the password. After each generation attempt, th
Good catch! I was thinking of the underlying hash; technically HMAC is a signature.

2020-10-16 12:44 UTC, gwynne approved these changes

2020-10-16 12:45 UTC, merged