Add information on queue delegate hooks
vapor/docs pull request #559
Opened 2020-10-11 22:37 UTC by jdmcd

Adds a few paragraphs on how to use the new Queue `JobEventDelegate` feature

2020-11-02 10:22 UTC, 0xTim requested changes
LGTM just one minor change

2020-11-02 10:22 UTC, 0xTim commented on 4.0/docs/queues.md
> +To get started, conform an object to JobEventDelegate and implement any of the methods you'd like:
Nit should be monospaced and tighten up the language

```suggestion
To get started, conform an object to `JobEventDelegate` and implement any required methods
```

2021-10-01 04:09 UTC, jdmcd commented
@0xTim cleaning out my old PRs and found one from a year ago 😅 implemented your suggested change

2021-10-01 10:48 UTC, 0xTim approved these changes

2021-10-01 10:48 UTC, merged