Update CORS docs with RouteLoggingMiddleware
vapor/docs pull request #562
Opened 2020-11-03 10:18 UTC by 0xTim

Update the docs to include the RouteLoggingMiddleware when creating CORS since you need to create your own middleware from scratch﻿

2020-11-03 10:32 UTC, gwynne requested changes

2020-11-03 10:32 UTC, gwynne commented on 4.0/docs/middleware.md
> +// Only if you want to enable the default per-route loggin
```suggestion
// Only add this if you want to enable the default per-route logging
```

2020-11-03 10:32 UTC, gwynne commented on 4.0/docs/middleware.md
> +// Add the defautl error middleware
```suggestion
// Add the default error middleware
```

2020-11-03 10:44 UTC, 0xTim commented
And this is why we do reviews! Changes made @gwynne

2020-11-20 11:49 UTC, MrLotU approved these changes

2020-11-20 12:08 UTC, merged