[Redis] -- Add overview and sessions documentation
vapor/docs pull request #569
Opened 2020-11-25 08:58 UTC by Mordil

2020-11-25 08:59 UTC, Mordil commented on 4.0/docs/redis/sessions.md
> +    return client.hmset(data.storage, in: RedisKey(id.string))
@0xTim I know that this API isn't exposed yet, so should I just remove this section on the Hash example, and we put it in later?

2020-11-25 14:01 UTC, 0xTim requested changes
A few comments and queries

2020-11-25 14:01 UTC, 0xTim commented on 4.0/docs/redis/sessions.md
> +Unless you implement the [`makeNewID()`](https://api.vapor.codes/redis/master/Redis/RedisSessionsDelegate/#redissessionsdelegate.makeNewID()) method in [your own `RedisSessionsDelegate`](#RedisSessio
Is this true if using the default sessions middleware?

2020-11-25 16:52 UTC, Mordil commented on 4.0/docs/sessions.md
> +The first step for enabling the Redis sessions driver:
🤦 This isn't a nit, this is just correcting poor guide writing haha

2020-11-25 17:05 UTC, Mordil commented on 4.0/docs/redis/sessions.md
> +Unless you implement the [`makeNewID()`](https://api.vapor.codes/redis/master/Redis/RedisSessionsDelegate/#redissessionsdelegate.makeNewID()) method in [your own `RedisSessionsDelegate`](#RedisSessio
Yes, there is a [default implementation](https://github.com/vapor/redis/blob/master/Sources/Redis/Redis%2BSessions.swift#L27) of the `makeNewID()` protocol requirement on the `RedisSessionsDelegate` itself, and the [`DefaultSessionsDriverDelegate`](https://github.com/vapor/redis/blob/master/Sources/Redis/Redis%2BSessions.swift#L92) only implements the required methods.

Why? Is this horrible semantics?

2020-11-26 11:24 UTC, 0xTim commented on 4.0/docs/redis/sessions.md
> +Unless you implement the [`makeNewID()`](https://api.vapor.codes/redis/master/Redis/RedisSessionsDelegate/#redissessionsdelegate.makeNewID()) method in [your own `RedisSessionsDelegate`](#RedisSessio
Oh hang on, is this just the name of the session in Redis? I was getting confused between the name of the cookie. In which case this is fine

2020-11-26 11:25 UTC, 0xTim approved these changes
@Mordil this looks good to go. I'll leave it open, as soon as vapor/redis is ready to be tagged feel free to merge the PR and then link to the docs in the release notes

2020-11-26 13:54 UTC, Mordil commented on 4.0/docs/redis/sessions.md
> +Unless you implement the [`makeNewID()`](https://api.vapor.codes/redis/master/Redis/RedisSessionsDelegate/#redissessionsdelegate.makeNewID()) method in [your own `RedisSessionsDelegate`](#RedisSessio
No it is the name of the session itself, not just the Redis key.

`makeNewID` is called when the `SessionDriver.createSession` method is called

https://github.com/vapor/redis/blob/5255824185c836aef5514d1d9e571571653d8569/Sources/Redis/Redis%2BSessions.swift#L70

Now that you’re bringing it up, it sounds like this should be the token itself but only the Redis key.

I’ll patch Redis and update these docs

2020-11-26 23:22 UTC, Mordil commented on 4.0/docs/redis/sessions.md
> +Unless you implement the [`makeNewID()`](https://api.vapor.codes/redis/master/Redis/RedisSessionsDelegate/#redissessionsdelegate.makeNewID()) method in [your own `RedisSessionsDelegate`](#RedisSessio
Redis patch(es):
- https://github.com/vapor/redis/pull/176
- https://github.com/vapor/redis/pull/177

2020-11-26 23:23 UTC, Mordil commented
@0xTim It looks like I don't have write access to the `master` branch.

> You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request.

2020-11-27 10:13 UTC, 0xTim commented
@Mordil permissions should be correct now

2020-11-27 23:15 UTC, 0xTim approved these changes

2020-11-27 23:15 UTC, merged