Group auth routes example by closure
vapor/docs pull request #577
Opened 2020-12-11 23:00 UTC by Lloople

I think this way it's easier to understand at a glance what's going on. 

I've also added a brief reference to routes.swift file.

2020-12-12 09:53 UTC, 0xTim requested changes

2020-12-12 09:53 UTC, 0xTim commented on 4.0/docs/routing.md
> +A route specifies a request handler for a given HTTP method and URI path. It can also store additional metadata. All routes are registered in `routes.swift` file.
This is misleading I'd say. It's certainly possible to add all routes in routes.swift but you don't want to register every route there (since you could end up with a file that 1000s of lines long). You can register routes with a `RouteCollection` and register the `RouteCollection` in routes.swift, but you can register a `RouteCollection` inside a `RouteCollection` etc etc. This also assumes that you're using the default template, which some people might now be. I think this should be changed to "you can register routes in routes.swift"

2020-12-12 09:53 UTC, 0xTim commented on 4.0/docs/routing.md
> +app.group(AuthMiddleware()) { auth in
I'm not personally a fan of the nesting (since you can end up in a pyramid of doom with futures and we want to avoid any additional nesting if we can). I think we could offer both options here.

2020-12-12 14:25 UTC, jonny7 commented on 4.0/docs/routing.md
> +app.group(AuthMiddleware()) { auth in
I had the same thoughts on this as you. I do think it makes it more complex rather than less complex to a newcomer

2021-01-13 11:12 UTC, 0xTim requested changes
I think we should be less ambiguous with the options we provide people and give them the 'best practice' as the main option

2021-01-13 11:12 UTC, 0xTim commented on 4.0/docs/routing.md
> +
Nit remove empty line

2021-01-13 11:12 UTC, 0xTim commented on 4.0/docs/routing.md
> +        routes.get("login") { req in ... }
These should probably be split out into functions instead of using the closure based approach to avoid `boot(routes:)` becoming massive itself

2021-01-13 11:12 UTC, 0xTim commented on 4.0/docs/routing.md
> +	routes.get("register") { req in ... }
Nit - line spacing

2021-01-13 11:12 UTC, 0xTim commented on 4.0/docs/routing.md
> +### Methods
I don't think this should be in the docs. This doesn't really solve any issue and people can work this out for themselves if they really want. Controllers should be the recommended approach

2021-12-29 10:34 UTC, closed without merging