Add optional child documentation
vapor/docs pull request #591
Opened 2021-03-04 22:56 UTC by fananek

Add optional child documentation

2021-03-04 23:32 UTC, gwynne approved these changes
Looks good, just a few grammatical nitpicks!

2021-03-04 23:32 UTC, gwynne commented on 4.0/docs/fluent/relations.md
> +    Ommiting child's unique constraint on parent id field can lead to unpredictable results.
```suggestion
    Omitting the unique constraint on the parent ID field from the client's schema can lead to unpredictable results.
```

2021-03-04 23:32 UTC, gwynne commented on 4.0/docs/fluent/relations.md
> +Child uniqueness should be enforced by `.unique` constraint in child database schema.
```suggestion
The one-to-one nature of the relation should be enforced in the child model's schema using a `.unique` constraint on the column referencing the parent model.
```

2021-03-04 23:32 UTC, gwynne commented on 4.0/docs/fluent/relations.md
> +    It means there can potentially exist multiple children while query result will always return the first one.
If there is no uniqueness constraint, the child table may wind up containing more than one child row for any given parent; in this case, an `@OptionalChild` property will still only be able to access one child at a time, with no way of controlling which child is loaded. If you may need to store multiple child rows for any given parent, use `@Children` instead.

2021-03-05 08:40 UTC, fananek commented on 4.0/docs/fluent/relations.md
> +    It means there can potentially exist multiple children while query result will always return the first one.
Docs updated as suggested.

2021-03-05 13:36 UTC, fananek commented
@gwynne Thanks for suggestions. PR should be ready for merge now. 👍

2021-03-05 21:08 UTC, 0xTim requested changes
Last few nits

2021-03-05 21:08 UTC, 0xTim commented on 4.0/docs/fluent/relations.md
> +mars.$governor.create(john, on: database)
Nit, this is wrong
```suggestion
mars.$governor.create(Jane, on: database)
```

2021-03-05 21:08 UTC, 0xTim commented on 4.0/docs/fluent/relations.md
> +    If there is no uniqueness constraint, the child table may wind up containing more than one child row for any given parent; in this case, an @OptionalChild property will still only be able to acce
Nit - wrap the property wrappers in code blocks

```suggestion
    If there is no uniqueness constraint, the child table may wind up containing more than one child row for any given parent; in this case, an `@OptionalChild` property will still only be able to access one child at a time, with no way of controlling which child is loaded. If you may need to store multiple child rows for any given parent, use `@Children` instead.
```

2021-03-06 09:29 UTC, 0xTim approved these changes
LGTM!

2021-03-06 09:29 UTC, 0xTim commented on 4.0/docs/fluent/relations.md
> +mars.$governor.create(Jane, on: database)
This should be lowercase, looks like an autocorrect on my part. I can fix this 
```suggestion
mars.$governor.create(jane, on: database)
```

2021-03-06 09:30 UTC, merged