Add information about creating tables with circular relations
vapor/docs pull request #642
Opened 2022-02-27 08:29 UTC by jboulter11

I've added some information about creating tables with circular relationships.  Specifically pointing out a common mistake about creating tables at the same time which relate to one-another.  I've suggested splitting the creation into two stages to avoid the issues with missing tables.

When I was creating my first tables, I ran into this error, which, after I resolved it, prompted this PR:
```
[ WARNING ] server: relation "table_name" does not exist (RangeVarGetRelidExtended)
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: server: relation "table_name" does not exist (RangeVarGetRelidExtended)
```

I'm new to Vapor/Fluent so let me know if this info is not good guidance/not correct.  Let me know what you'd like changed.

2022-05-06 15:14 UTC, 0xTim requested changes
@jboulter11 sorry for taking so long to get to this! I've got some comments, what do you think

2022-05-06 15:14 UTC, 0xTim commented on 4.0/docs/fluent/schema.md
> +The above constraint requires that all values in the "star_id" field must match one of the values in Star's "id" field, and that the "stars" table already exist.
```suggestion
The above constraint requires that all values in the `"star_id"` field must match one of the values in Star's `"id"` field, and that the `"stars"` table already exist.
```

2022-05-06 15:14 UTC, 0xTim commented on 4.0/docs/fluent/relations.md
> +```
This is schema stuff so should live elsewhere, I suggest we remove it

2022-05-06 15:14 UTC, 0xTim commented on 4.0/docs/fluent/relations.md
> +!!! warning Since this relation does not store any values, no database schema entry is required for the parent table.  Creating one will likely lead to errors like `server: null value in column "plan
I think the changes in this file can be reverted. I think they'll confuse more than help

2023-08-27 21:52 UTC, dannflor commented
Closing as stale.

2023-08-27 21:52 UTC, closed without merging