WIP: Add docs for deployment on Fly
vapor/docs pull request #724
Opened 2022-09-02 23:57 UTC by PopFlamingo

2022-09-03 00:16 UTC, PopFlamingo commented
Some code examples in this document are currently based on the this Fluent PR:
https://github.com/vapor/docs/pull/724

And will evolve depending on it.

2022-09-05 21:17 UTC, BennyDeBock commented on docs/deploy/fly.md
> +> The code snippet above assumes you are using the default Vapor Dockerfile which sets your app `ENTRYPOINT` to `./Run`. Concretely, this means that when you set `release_command` to `migrate -y`, Fl
Suggestion to change 
`>`

To 

`!!! Note`

This will pull more attention to it as it is something quite important

2022-09-05 21:17 UTC, BennyDeBock commented on docs/deploy/fly.md
> +> Tip: Keep in mind that most shells keep an history of the commands you typed. Be cautious about this when setting secrets this way. Some shells can be configured to not remember commands that are p
Same as above, but with `!!! Tip`

2022-09-06 06:18 UTC, BennyDeBock reviewed
A few small nitpicks but looking good overall

2022-09-06 06:18 UTC, BennyDeBock commented on docs/deploy/fly.md
> +> Commands specified in this document are subject to [Fly's pricing](https://fly.io/docs/about/pricing/), make sure you understand it properly before continuing.
Change `>` to `!!! note`

2022-09-06 06:18 UTC, BennyDeBock commented on docs/deploy/fly.md
> +First, make sure your current directory is set to the root of your Vapor repository and run the following command:
I'd change this
`root of your Vapor repository` => `root directory of your Vapor application`

2022-09-06 06:18 UTC, BennyDeBock commented on docs/deploy/fly.md
> +> Tip: when your current directory is in your app's root, the fly CLI tool automatically detects the presence of a `fly.toml` file which lets Fly know which app your commands are targetting. If you w
Change `>` to `!!! tip`

2022-09-06 06:18 UTC, BennyDeBock commented on docs/deploy/fly.md
> +## Configuring Postgres
Just a question. Any plans to include the steps for MySQL as well? I found out that they do have instructions on that [found here](https://fly.io/docs/app-guides/mysql-on-fly/).

2022-09-06 06:18 UTC, BennyDeBock commented on docs/deploy/fly.md
> +> Note that the difference between `fly pg create` and `fly pg attach` is that the former allocates and configures a Fly app that will be able to host Postgres databases, while the latter creates an
change `>` to `!!! note`

2022-09-06 09:54 UTC, 0xTim reviewed
This is a great start thanks! I've added a few comments

2022-09-06 09:54 UTC, 0xTim commented on docs/deploy/fly.md
> +- **Database:** you can ask Fly to create a database to use with your app. If you prefer, you can always do the same later with the `fly pg create` and `fly pg attach` commands (see the [Configuring
Would be good to mention if there's a free tier here

2022-09-06 09:54 UTC, 0xTim commented on docs/deploy/fly.md
> +
We only need one empty line here 😅

2022-09-06 09:54 UTC, 0xTim commented on docs/deploy/fly.md
> +if let databaseURL = Environment.get("DATABASE_URL") {
Does Fly require TLS connections for Postgres?

2022-09-06 21:47 UTC, PopFlamingo commented on docs/deploy/fly.md
> +This will start an interactive prompt for multiple of your Fly app's settings, including:
Thanks that's much clearer indeed

2022-09-06 21:50 UTC, PopFlamingo commented on docs/deploy/fly.md
> +> Commands specified in this document are subject to [Fly's pricing](https://fly.io/docs/about/pricing/), make sure you understand it properly before continuing.
What do you think of something like this?
> ⚠️ Note:

2022-09-06 22:21 UTC, PopFlamingo commented on docs/deploy/fly.md
> +If you want to create a new project from scratch, first ensure you have installed the Vapor toolbox (see install the instructions for [macOS](../install/macos.md#install-toolbox) or [Linux](../instal
What generated templates are you referring to?

2022-09-06 23:23 UTC, PopFlamingo commented on docs/deploy/fly.md
> +if let databaseURL = Environment.get("DATABASE_URL") {
It doesn't since the connection is made through their internal Wireguard network: https://fly.io/docs/reference/private-networking/

2022-09-07 00:10 UTC, PopFlamingo commented on docs/deploy/fly.md
> +- **Database:** you can ask Fly to create a database to use with your app. If you prefer, you can always do the same later with the `fly pg create` and `fly pg attach` commands (see the [Configuring
Fly has an option for a "dev" database which corresponds to a single instance running the database app. The issue is that this isn't free per se: it is only free if it stays within the global free allowance, so it depends on how many apps the user is currently running.

2022-09-07 00:13 UTC, PopFlamingo commented
@BennyDeBock @0xTim Thanks a lot for the feedback! Applied some changes already and asked more questions for some comments.

2022-09-07 07:08 UTC, BennyDeBock commented on docs/deploy/fly.md
> +If you want to create a new project from scratch, first ensure you have installed the Vapor toolbox (see install the instructions for [macOS](../install/macos.md#install-toolbox) or [Linux](../instal
These are the templates I meant. When the template that the toolbox uses changes, these templates are auto-generated. This makes it so that people don't necessarily have to install the toolbox to start using Vapor.

https://github.com/vapor/template-fluent-postgres
https://github.com/vapor/template-fluent-mysql
https://github.com/vapor/template-bare
https://github.com/vapor/template-fluent-postgres-leaf

2022-09-07 07:11 UTC, BennyDeBock commented on docs/deploy/fly.md
> +> Commands specified in this document are subject to [Fly's pricing](https://fly.io/docs/about/pricing/), make sure you understand it properly before continuing.
I'd still change it to what I proposed. This is because it automatically transforms into one of these:

![image](https://user-images.githubusercontent.com/74614235/188812245-21f7c3b3-8dcf-4949-b683-a60ebd3a720a.png)


In this example, you'd list it as 
```md
!!! note
    Commands specified in this document are subject to [Fly's pricing](https://fly.io/docs/about/pricing/), make sure you understand it properly before continuing.
```
Where the empty space is a tab. You have multiple of those you can use. e.g. note, warning, danger, tip, etc

2022-09-07 19:15 UTC, PopFlamingo commented on docs/deploy/fly.md
> +> Commands specified in this document are subject to [Fly's pricing](https://fly.io/docs/about/pricing/), make sure you understand it properly before continuing.
@BennyDeBock That's great! Didn't know about this syntax, I'll change it to this then 👍

2022-09-07 19:26 UTC, PopFlamingo commented on docs/deploy/fly.md
> +## Configuring Postgres
It could be a good idea indeed, I wonder what parts should be included exactly: with Postgres it was quite easy to make a simple step by step tutorial since the Fly CLI already has a really good integration with it. The MySQL setup has to be done in a less automated way. I suppose it might be possible to link the instructions for setting up the MySQL app, and then simply explaining how to connect to it in Swift with this document.

2022-09-08 10:37 UTC, 0xTim commented on docs/deploy/fly.md
> +## Configuring Postgres
I think sticking with one DB in our docs is fine and just pointing to other docs as needed

2022-09-08 10:37 UTC, 0xTim commented on docs/deploy/fly.md
> +- **Database:** you can ask Fly to create a database to use with your app. If you prefer, you can always do the same later with the `fly pg create` and `fly pg attach` commands (see the [Configuring
Ok we should definitely mention that then and what the limits are (or link to them)

2022-09-08 23:04 UTC, PopFlamingo commented on docs/deploy/fly.md
> +If you want to create a new project from scratch, first ensure you have installed the Vapor toolbox (see install the instructions for [macOS](../install/macos.md#install-toolbox) or [Linux](../instal
I see, yeah I think it would make a lot of sense indeed, thank you!

2022-09-08 23:05 UTC, PopFlamingo commented on docs/deploy/fly.md
> +## Configuring Postgres
Will do this then 👍

2022-09-08 23:20 UTC, PopFlamingo commented on docs/deploy/fly.md
> +- **Database:** you can ask Fly to create a database to use with your app. If you prefer, you can always do the same later with the `fly pg create` and `fly pg attach` commands (see the [Configuring
I placed a warning at the beginning of the document about the pricing. Do you mean I should be specifying that additional costs might occur when creating a database, or just indicating the existence of a free tier? What worries me about adding more details is that Fly's pricing can change at any time, and there is also an unbounded cost (bandwidth) which means free fly apps might not be free anymore past the bandwidth allowance, so if I mention the free tier I feel like I should also be mentioning the reasons why it might be exceeded.

2022-09-08 23:39 UTC, PopFlamingo commented on docs/deploy/fly.md
> +If your release command fails, the deployment won't continue.
@BennyDeBock Please let me know what you think about this

2022-09-08 23:40 UTC, PopFlamingo commented on docs/deploy/fly.md
> +While Fly makes it easy to create a Postgres database app, it is possible to host other types of databases as well (for instance, see ["Use a MySQL database"](https://fly.io/docs/app-guides/mysql-on-
@BennyDeBock Please let me know what you think about this

2022-09-09 00:46 UTC, PopFlamingo commented on docs/deploy/fly.md
> +If you want to create a new project from scratch, first ensure you have installed the Vapor toolbox (see install the instructions for [macOS](../install/macos.md#install-toolbox) or [Linux](../instal
@BennyDeBock Added a section about it, let me know what you think! 🙂

2022-09-12 06:28 UTC, BennyDeBock commented on docs/deploy/fly.md
> +While Fly makes it easy to create a Postgres database app, it is possible to host other types of databases as well (for instance, see ["Use a MySQL database"](https://fly.io/docs/app-guides/mysql-on-
LGTM

2022-09-12 06:31 UTC, BennyDeBock commented on docs/deploy/fly.md
> +If you want to create a new project from scratch, first ensure you have installed the Vapor toolbox (see install the instructions for [macOS](../install/macos.md#install-toolbox) or [Linux](../instal
I saw. LGTM

2022-09-14 21:18 UTC, PopFlamingo commented
@0xTim I believe this should be pretty close to being mergable, please let me know if you see anything else that should be improved

2022-11-30 15:11 UTC, mikaelacaron commented
Great write up @PopFlamingo ! I'm giving my conference talk on this topic! https://www.serversideswift.info/speakers/mikaela-caron/

2022-12-23 21:13 UTC, 0xTim requested changes
This looks great! I've got some suggestions to just tighten up the language. I'll see if I can get the vapor.team link fixed

2022-12-23 21:13 UTC, 0xTim commented on docs/deploy/fly.md
> +With most common Vapor project setups, you configure your database in the `configure.swift` file. Here is how you might want to do this:
```suggestion
With most common Vapor project setups, you configure your database in `configure.swift`. Here's how you might want to do this:
```

2022-12-23 21:13 UTC, 0xTim commented on docs/deploy/fly.md
> +While Fly makes it easy to create a Postgres database app, it is possible to host other types of databases as well (for instance, see ["Use a MySQL database"](https://fly.io/docs/app-guides/mysql-on-
```suggestion
While Fly makes it easy to create a Postgres database app, it is possible to host other types of databases as well (for instance, see ["Use a MySQL database"](https://fly.io/docs/app-guides/mysql-on-fly/) in the Fly Docs).
```

2022-12-23 21:13 UTC, 0xTim commented on docs/deploy/fly.md
> +Use secrets to set any sensitive environment variable.
```suggestion
Use secrets to set any sensitive values as environment variables.
```

2022-12-23 21:13 UTC, 0xTim commented on docs/deploy/fly.md
> +Now that your Vapor app is deployed, there is a lot more you can do such as scaling your apps vertically and horizontally across multiple regions, adding persistent volumes, setting up continuous dep
```suggestion
Now that your Vapor app is deployed, there is a lot more you can do such as scaling your apps vertically and horizontally across multiple regions, adding persistent volumes, setting up continuous deployment, or even creating distributed app clusters. The best place to learn how to do all of this and more is the [Fly docs](https://fly.io/docs/).
```

2023-01-19 19:43 UTC, 0xTim approved these changes

2023-01-19 19:47 UTC, merged