add tip about session cookie
vapor/docs pull request #760
Opened 2023-01-20 21:13 UTC by henrikac

This PR adds a small tip/note about session cookie not being set to `secure` and `httpOnly` by default. This was something randomly noticed when I was figuring out how to set up authentication and I thought this might be a helpful tip to others.

2023-01-22 01:36 UTC, jdmcd requested changes
Thank you! One grammatical suggestion

2023-01-22 01:36 UTC, jdmcd commented on docs/security/authentication.md
> +    The session cookie is not set to `secure` and `httpOnly` by default. Check Vapor's [Session API](../advanced/sessions.md#configuration) how to configure cookies.
```suggestion
    The session cookie is not set to `secure` and `httpOnly` by default. Check Vapor's [Session API](../advanced/sessions.md#configuration) for more information on how to configure cookies.
```

2023-01-22 07:33 UTC, henrikac commented on docs/security/authentication.md
> +    The session cookie is not set to `secure` and `httpOnly` by default. Check Vapor's [Session API](../advanced/sessions.md#configuration) how to configure cookies.
Thank you for the suggestion :)

2023-01-25 16:15 UTC, jdmcd approved these changes

2023-01-25 16:16 UTC, jdmcd commented
@0xTim @gwynne do we merge despite the dead link CI failure? I see other PRs have been merged in that state so I'm not sure.

2023-01-27 23:22 UTC, 0xTim commented
@jdmcd I'm planning on fixing the API docs this weekend - if I don't do it by then, then we can merge

2023-02-05 19:33 UTC, henrikac commented
Any update on if this can be merged or not? :) @jdmcd @0xTim

2023-02-05 20:41 UTC, 0xTim commented
Yeah we can merge this, I've hit a crash with DocC that's blocking the API docs.

Thanks for the PR!

2023-02-05 20:42 UTC, merged