Update Digital Ocean deploy
vapor/docs pull request #765
Opened 2023-02-04 04:57 UTC by Tyler-Waitt

Hi all. This is my first PR (for any project!). Please let me know if I messed anything up. I saw [this issue](https://github.com/vapor/docs/issues/764) on the Digital Ocean deployment docs being out of date and gave it a go. Thanks!

2023-02-04 05:05 UTC, Tyler-Waitt commented
Also, I ran into [this bug](https://github.com/vapor/vapor/issues/2681) when working on this guide on Digital Ocean. Adding a swap following [this guide](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04) fixed it. I don't know if that should go in as a note.

2023-02-05 20:39 UTC, 0xTim requested changes
Thanks for doing this! I have one question around the port.

We can probably point people to the Vapor docs for installing Swift and the toolbox rather than duplicating it here, but until installing Swift is easier I'm happy to keep it

2023-02-05 20:39 UTC, 0xTim commented on docs/deploy/digital-ocean.md
> +vapor run serve --hostname 0.0.0.0 --port 80 &
Does this work? I'd expect to need sudo privileges to run on port 80 (which it shouldn't have!)

I'm fine with using 8080 and opening up the firewall to that port instead.

We also probably don't want to immediately background the process for the demo

2023-02-05 21:45 UTC, Tyler-Waitt commented on docs/deploy/digital-ocean.md
> +vapor run serve --hostname 0.0.0.0 --port 80 &
Oh, you're right. It would be better to do all of this on 8080. I think I was on root 😬

2023-02-05 21:57 UTC, Tyler-Waitt commented on docs/deploy/digital-ocean.md
> +vapor run serve --hostname 0.0.0.0 --port 8080
Background process removed too

2023-02-05 23:20 UTC, 0xTim approved these changes
Great thanks!

2023-02-05 23:26 UTC, merged