Example to populate pivot properties
vapor/docs pull request #815
Opened 2023-06-02 23:39 UTC by alemohamad

Add explanation on how to use the closure method in attach method to populate properties in pivot model.

2023-06-03 01:04 UTC, gwynne requested changes
Looks good, but I've recommended some tweaks for grammar and completeness.

2023-06-03 01:04 UTC, gwynne commented on docs/fluent/relations.md
>  }
GitHub doesn't allow me to leave comments directly on lines that weren't modified in the original PR, but given the new example code below, these additional fields should be added to the `PlanetTag` model starting at line 151:

```swift
    @OptionalField(key: "comments")
    var comments: String?
    
    @OptionalEnum(key: "status")
    var status: PlanetTagStatus?

```
And, to be really and truly pedantic, the `PlanetTagStatus` enum should be defined somewhere to; I'd just sneak it in after line 140:
```swift
    enum PlanetTagStatus: String, Codable { case accepted, pending }
```

2023-06-03 09:31 UTC, alemohamad commented
Thanks @gwynne for your feedback! I believe that this adds more context to the readers. The changes are already applied. 👍

2023-06-03 09:53 UTC, gwynne approved these changes

2023-06-05 11:50 UTC, 0xTim approved these changes
Thanks!

2023-06-05 11:54 UTC, merged