Add Spanish translation for linux.md
vapor/docs pull request #823
Opened 2023-06-06 21:07 UTC by alemohamad

Added Spanish translation for linux.md.

2023-06-07 07:22 UTC, jacostaf10 approved these changes
LGTM, natively correct

2023-06-08 14:37 UTC, 0xTim requested changes

2023-06-08 14:37 UTC, 0xTim commented on docs/install/linux.es.md
> +Para usar Vapor, necesitas Swift 5.2 o superior. Se puede instalar usando las opciones disponibles en [Swift.org](https://swift.org/download/).
```suggestion
Para usar Vapor, necesitas Swift 5.6 o superior. Se puede instalar usando las opciones disponibles en [Swift.org](https://swift.org/download/).
```
Nosotros ahora requerimos 5.6 o superior

2023-06-08 14:37 UTC, 0xTim commented on docs/install/linux.es.md
> +Vapor admite las mismas versiones de distribución de Linux que adminte Swift 5.2 o versiones más recientes.
```suggestion
Vapor admite las mismas versiones de distribución de Linux que adminte Swift 5.6 o versiones más recientes.
```

2023-06-08 14:37 UTC, 0xTim commented on docs/install/linux.es.md
> +|Ubuntu|16.04, 18.04|>= 5.2|
16.04 y 18.04 no son compatibles

2023-06-08 14:37 UTC, 0xTim commented on docs/install/linux.es.md
> +|Ubuntu|20.04|>= 5.2.4|
```suggestion
|Ubuntu|20.04|>= 5.6|
```

2023-06-08 14:37 UTC, 0xTim commented on docs/install/linux.es.md
> +|Fedora|>= 30|>= 5.2|
```suggestion
|Fedora|>= 30|>= 5.6|
```

2023-06-08 14:37 UTC, 0xTim commented on docs/install/linux.es.md
> +|CentOS|8|>= 5.2.4|
```suggestion
|CentOS|8|>= 5.6|
```

2023-06-08 14:37 UTC, 0xTim commented on docs/install/linux.es.md
> +|Amazon Linux|2|>= 5.2.4|
```suggestion
|Amazon Linux|2|>= 5.6|
```

2023-06-09 08:49 UTC, alemohamad commented
@0xTim thanks for the change in the values! Should we update all of them in the other translations (even English)? Maybe I can do this in this PR. Please let me know.

2023-06-09 08:56 UTC, alemohamad commented on docs/install/linux.es.md
> +|Ubuntu|16.04, 18.04|>= 5.2|
@0xTim Should we change them to another Ubuntu version(s)?

2023-06-11 11:24 UTC, 0xTim commented
@alemohamad Yeah if you can do them in this PR that would be great!

2023-06-11 14:22 UTC, alemohamad commented
@0xTim updated values in another translations. 😉

2023-06-12 13:44 UTC, 0xTim approved these changes
Great thank you!

2023-06-12 13:44 UTC, merged