Request
vapor/docs pull request #860
Opened 2023-07-19 16:43 UTC by dannflor

This is my own attempt to close #394 with a full request page. May supersede #859 if we want a more in depth section.

2023-07-20 01:22 UTC, 0xTim requested changes
Thanks for this! Few tweaks but really good additions!

2023-07-20 01:22 UTC, 0xTim commented on docs/advanced/request.md
> +The `SocketAddress` representing the client can be accessed via `Request.remoteAddress`, which may be useful for logging or rate limiting using the string representation `Request.remoteAddress.ipAddr
I'd like to see a code example of accessing this, what type it is etc rather than it being all inline

2023-07-20 01:22 UTC, 0xTim commented on docs/advanced/request.md
> +## Authentication
We should remove this section as it's all duplicated - it could live in a separate package etc and not part of the main `Request` object

2023-07-20 01:22 UTC, 0xTim commented on docs/advanced/request.md
> +It is the main window into the rest of Vapor's functionality. It contains APIs for the [request body](../basics/content.md), [query parameters](../basics/content.md#query), [logger](../basics/logging
```suggestion
It is the main window into the rest of Vapor's functionality. It contains APIs for the [request body](../basics/content.md), [query parameters](../basics/content.md#query), [logger](../basics/logging.md), [HTTP client](../basics/client.md), and more. Accessing this functionality through the request keeps computation on the correct event loop and allows it to be mocked for testing. You can even add your own services to the `Request` with extensions.
```

2023-07-28 20:06 UTC, 0xTim commented on docs/advanced/request.md
> +## Authentication
Sorry this was about Authentication and not Application 😅

2023-07-28 20:10 UTC, 0xTim requested changes
One change then we're good I think

2023-08-02 22:57 UTC, gwynne requested changes
A few minor nits, but overall excellent!!

2023-08-02 22:57 UTC, gwynne commented on docs/advanced/request.md
> +The `Request.application` property holds a reference to the [`Application`](https://api.vapor.codes/vapor/documentation/vapor/application). This object contains all of the configuration and core func
```suggestion
The `Request.application` property holds a reference to the [`Application`](https://api.vapor.codes/vapor/documentation/vapor/application). This object contains all of the configuration and core functionality for the application. Most of it should only be set in `configure.swift`, before the application fully starts, and many of the lower level APIs won't be needed in most applications. One of the most useful properties is `Application.eventLoopGroup`, which can be used to get an `EventLoop` for processes that need a new one via the `any()` method. It also contains the [`Environment`](../basics/environment.md).
```

2023-08-02 22:57 UTC, gwynne commented on docs/advanced/request.md
> +    guard let contentType = req.headers.first(name: "Content-Type") else {
```suggestion
    guard let contentType = req.headers.contentType, contentType == .json else {
```

2023-08-02 22:57 UTC, gwynne commented on docs/advanced/request.md
> +See further documentation for `HTTPHeaders` [here](https://swiftpackageindex.com/apple/swift-nio/2.56.0/documentation/niohttp1/httpheaders).
```suggestion
See further documentation for `HTTPHeaders` [here](https://swiftpackageindex.com/apple/swift-nio/2.56.0/documentation/niohttp1/httpheaders). Vapor also adds several extensions to `HTTPHeaders` to make working with the most commonly-used headers more easily; a list is available [here](https://api.vapor.codes/vapor/documentation/vapor/niohttp1/httpheaders#instance-properties)
```

2023-08-03 20:40 UTC, dannflor commented
@gwynne

2023-08-03 21:06 UTC, gwynne approved these changes

2023-08-05 16:34 UTC, 0xTim approved these changes
Thanks!

2023-08-05 16:39 UTC, merged