Add new templates for vapor/penny-bot#81
vapor/docs pull request #867
Opened 2023-07-26 17:09 UTC by MahdiBM

Adds new leaf templates that can be used with vapor/penny-bot#81.

We should not remove the old templates for now, until Penny has shown some success.

2023-07-26 17:33 UTC, 0xTim commented on .github/templates/translation_needed.description.leaf
> +The docs have been updated in PR #(number). The translations should be updated if required.
Will the link be auto-created here?

2023-07-26 17:34 UTC, MahdiBM commented on .github/templates/translation_needed.description.leaf
> +The docs have been updated in PR #(number). The translations should be updated if required.
Yes it'll appear as a proper link on GitHub.

2023-07-26 17:37 UTC, MahdiBM commented
Removed the title template as we can just use that in Penny repo.
Moved the description template on level higher to `.github`.

2023-07-26 17:40 UTC, MahdiBM commented on .github/templates/translation_needed.description.leaf
> +The docs have been updated in PR #(number). The translations should be updated if required.
like `#867`: #867

2023-07-26 17:41 UTC, MahdiBM commented
not sure if i should move the template file down to `/workflows`. 
didn't put it there because it's technically not used by GHA workflows anymore.

2023-07-27 09:58 UTC, MahdiBM commented on .github/templates/translation_needed.description.leaf
> +The docs have been updated in PR #(number). The translations should be updated if required.
ahhhh now i see ... i need to use `in PR ##(number).` instead of `updated in PR #(number).` Considering one `#` is used by leaf syntax. Updated the PR.

2023-07-27 15:52 UTC, 0xTim requested changes
Can you update the README to ensure people know to update this file when adding new translations? I think we can just point people at this rather than getting them to use both as it will be the way to do it soon enough

2023-07-27 16:07 UTC, MahdiBM commented
the build failure is normal. The new README contains a link to the main branch but the file is not there because this PR is not merged yet.

2023-07-27 17:19 UTC, 0xTim approved these changes

2023-07-27 17:19 UTC, merged