Translate authentication.md to german
vapor/docs pull request #889
Opened 2023-08-27 18:09 UTC by mezotv

Adds the correct and finished German translation for the authentication.md file. Also fixes the index.de.md translation!

This is the complete and improved version of #827

2023-08-27 18:10 UTC, mezotv commented
If I missed anything let me know and I will add that as soon as possible!

2023-08-27 18:30 UTC, mezotv commented
Hey @ptoffy would you be able to check this out?

2023-08-27 21:20 UTC, ptoffy submitted a review, later dismissed
I reviewed until line ~100 and have found quite some missing pieces. Please review the file and fix the pieces you can find, then I'm happy to fix the left overs! (If @mattesmohr isn't faster 😄)

2023-08-27 21:41 UTC, mezotv commented
> I reviewed until line ~100 and have found quite some missing pieces. Please review the file and fix the pieces you can find, then I'm happy to fix the left overs! (If @mattesmohr isn't faster 😄)

Yea I didn't check the first half seems like matt left a bit out ill get that fixed!

2023-08-27 21:57 UTC, mezotv commented on docs/security/authentication.de.md
> +| `CredentialsAuthenticator`/`AsyncCredentialsAuthenticator`  |Authenticates a credentials payload from the request body.|
Resolved!

2023-08-27 21:58 UTC, mezotv commented
@ptoffy I have added the necessary changes let me know if you find something!

2023-08-28 15:20 UTC, mattesmohr commented
Hiya Dominik, I hope you don't mind I hope in. Paul and I have talked and we think I should do the review, since I have started the initial translation for the authentication.md. First, thank you for taking the time to finish the translation. I appreciate it. I will take a look at least at the end of the week, as I write you in between two appointments right now and the rest of the week doesn't look different.

Since this is about the German translation, I think it is totally fine to express ourself in German.

2023-09-25 15:06 UTC, ptoffy commented
Hey @mattesmohr, do you have any update on this? :)

2023-09-26 06:53 UTC, mattesmohr commented
> Hey @mattesmohr, do you have any updates on this? :)

Yes and no. I am back from vacation and I have some time to spare. Will finish the review this week.

2023-10-01 19:32 UTC, mattesmohr requested changes
Anbei die erste Hälfte des Reviews. Mehr habe ich heute nicht geschafft.

2023-10-01 19:32 UTC, mattesmohr commented on docs/security/authentication.de.md
> +Um einen Benutzer und zukünftige Anfragen mit einer Sitzung zu authentifizieren, musst du einen Benutzer anmelden. Vapor bietet ein `ModelCredentialsAuthenticatable`-Protokoll, dem du entsprechen mus
```suggestion
Um einen Benutzer und bestehende Sitzungen zu authentifizieren, muss sich zuerst ein Benutzer anmelden. Vapor stellt uns für die Anmeldungsabwicklung das Protokoll _ModelCredentialsAuthenticatable_ zur Verfügung, mit das wir unser Objekt _User_ versehen. 
```

2023-10-01 19:35 UTC, mezotv commented
> Anbei die erste Hälfte des Reviews. Mehr habe ich heute nicht geschafft.

Sehr cool danke! Leider hab ich kaum zeit mehr werde mir das ganze also erst mitte November anschauen können.

2023-10-03 09:50 UTC, mezotv commented on docs/index.de.md
> +Das Vapor Kernteam und viele andere Mitglieder der Vapor Community.
Gerne, kann ich machen!

2023-10-03 09:55 UTC, mezotv commented on docs/security/authentication.de.md
> +Vapor ermöglicht die [Basis](https://tools.ietf.org/html/rfc7617)- und [Bearer](https://tools.ietf.org/html/rfc6750) Authentifizierung mittels dem `Authorization` Header. Man kann auch einen User mit
Arbeite leider nicht mit Vapor darum kann ich hier nicht viel helfen.

2023-11-01 11:08 UTC, mattesmohr requested changes

2023-11-01 11:08 UTC, mattesmohr commented on docs/security/authentication.de.md
> +Diese Zusammensetzung von Authentifikatoren führt zu einer Route, auf die entweder mit einem Passwort oder einem Token zugegriffen werden kann. Ein solcher Weg könnte es einem Benutzer ermöglichen, s
```suggestion
Die Kombination aus den beiden oben genannten Authentifikatoren ermöglicht den Zugriff mit einem Passwort oder einem Token. Auf dieser Weise kann sich ein Benutzer anmelden um wiederum regelmäßig einen Token zu generieren.
```

2023-11-14 06:41 UTC, mezotv commented
Any update on this @mattesmohr @ptoffy ?ñ

2023-11-14 08:04 UTC, mattesmohr commented
@mezotv  Hiya, ich bin nicht ganz zufrieden, werde aber noch mit meiner Korrektur auf meiner Festplatte etwas brauchen. Ein, zwei Abschnitte sind noch übrig. Damit das PR mal erledigt wird, werde ich es, wenn die Test durchgelaufen und bestanden sind, nachher oder heute Abend mergen.

2023-11-14 17:39 UTC, mattesmohr approved these changes

2023-11-14 17:47 UTC, merged