Fix version and name of the VaporAPNS package
vapor/docs pull request #898
Opened 2023-09-10 03:32 UTC by jverkoey

Version 5.0 of Vapor's APNS package does not appear to exist (https://github.com/vapor/apns/releases).

2023-09-10 03:48 UTC, jverkoey commented
Oh. There appear to be two packages actually? These might not be the right edits just yet 😅

2023-09-14 09:39 UTC, 0xTim requested changes
Thanks for spotting this! If you could add a couple of extra bits we can get this merged!

2023-09-14 09:39 UTC, 0xTim commented on docs/advanced/apns.md
> +        .package(url: "https://github.com/vapor/apns.git", from: "4.0.0"),
This is correct but could you also add a dependency on https://github.com/swift-server-community/APNSwift and add `APNS` and `APNSCore` as target dependencies?

2023-09-14 09:39 UTC, 0xTim commented on docs/advanced/apns.md
> +import VaporAPNS
This is fine, we just need to import `APNS` and `APNSCore` as well

2023-11-16 01:47 UTC, closed without merging

2023-11-16 01:47 UTC, dannflor commented
Superseded by #943