Add Spanish translation for transaction.md
vapor/docs pull request #912
Opened 2023-09-25 07:28 UTC by jacostaf10

Added Spanish translation of `transaction.md` in `fluent`folder

2023-10-05 10:36 UTC, alemohamad commented on docs/fluent/transaction.es.md
> +Una vez dentro del closure de la transacción, debes usar la base de datos proporcionada en el parámetro del closure (llamado `database` en el ejemplo) para hacer consultas.
```suggestion
Para llevar a cabo una transacción, necesitas acceso a algo que pueda conectar con la base de datos. Normalmente, esto es una petición HTTP entrante. Para esto, usa `req.db.transaction(_ :)`:

```swift
req.db.transaction { database in
    // usar la base de datos
}
```

Una vez dentro del closure de la transacción, debes usar la base de datos proporcionada en el parámetro del closure (llamado `database` en el ejemplo) para hacer consultas.
```

2023-10-05 10:37 UTC, alemohamad commented on docs/fluent/transaction.es.md
> +req.db.transaction { database in
```suggestion
Para llevar a cabo una transacción, necesitas acceso a algo que pueda conectar con la base de datos. Normalmente, esto es una petición HTTP entrante. Para esto, usa `req.db.transaction(_ :)`:

```swift
req.db.transaction { database in
```

2023-10-05 10:37 UTC, alemohamad commented on docs/fluent/transaction.es.md
> +Una vez dentro del closure de la transacción, debes usar la base de datos proporcionada en el parámetro del closure (llamado `database` en el ejemplo) para hacer consultas.
```suggestion
}
```

Una vez dentro del closure de la transacción, debes usar la base de datos proporcionada en el parámetro del closure (llamado `database` en el ejemplo) para hacer consultas.
```

2023-10-05 10:37 UTC, alemohamad commented on docs/fluent/transaction.es.md
> +Una vez dentro del closure de la transacción, debes usar la base de datos proporcionada en el parámetro del closure (llamado `database` en el ejemplo) para hacer consultas.
```suggestion

Una vez dentro del closure de la transacción, debes usar la base de datos proporcionada en el parámetro del closure (llamado `database` en el ejemplo) para hacer consultas.
```

2023-10-05 10:40 UTC, alemohamad commented on docs/fluent/transaction.es.md
> +Cuando este closure devuelva de manera exitosa, se hará la transacción.
```suggestion
Cuando este closure devuelva de manera exitosa, se hará la transacción.

```

2023-10-05 10:40 UTC, alemohamad commented on docs/fluent/transaction.es.md
> +El ejemplo anterior guardará `sun` y *después* `sirius` antes de completar la transacción. Si falla el guardado de cualquiera de las estrellas, ninguna se guardará.
```suggestion

El ejemplo anterior guardará `sun` y *después* `sirius` antes de completar la transacción. Si falla el guardado de cualquiera de las estrellas, ninguna se guardará.
```

2023-10-05 10:41 UTC, alemohamad commented on docs/fluent/transaction.es.md
> +Una vez la transacción se haya completado, el resultado puede transformarse en un futuro diferente, como un estatus HTTP que indique la finalización, de manera similar al siguiente ejemplo:
```suggestion
Una vez la transacción se haya completado, el resultado puede transformarse en un futuro diferente, como una respuesta HTTP que indique la finalización, de manera similar al siguiente ejemplo:

```

2023-10-05 10:42 UTC, alemohamad requested changes
This looks great! Just a minor tweaks before ready to be merged.

2023-10-11 12:03 UTC, 0xTim commented
@alemohamad is this ready to go?

2023-10-13 19:12 UTC, alemohamad approved these changes

2023-10-13 19:12 UTC, alemohamad commented
@0xTim ready to go! 🚀

2023-10-16 19:39 UTC, merged