Update routing.md
vapor/docs pull request #920
Opened 2023-10-03 03:32 UTC by KalynDavis

Fixes typo on `Basics` docs section related to 'redirect(to:type:)' being deprecated and renamed to 'redirect(to:redirectType:)'

2023-10-03 23:32 UTC, 0xTim requested changes
@KalynDavis Thanks for this! Since this is just code changes could you update the different translations as well?

2023-10-03 23:32 UTC, 0xTim commented on docs/basics/routing.md
>  The different `RedirectType`s are:
This line needs to be updated as well
```suggestion
The different `Redirect`s are:
```

2023-10-05 22:30 UTC, KalynDavis commented on docs/basics/routing.md
>  The different `RedirectType`s are:
@0xTim shouldn't this still be `RedirectType's` since it is providing the different static members for `redirectType`?

2023-10-05 22:34 UTC, 0xTim commented on docs/basics/routing.md
>  The different `RedirectType`s are:
@KalynDavis `RedirectType` is now deprecated and the new type is `Redirect` so we should rename it just to avoid confusion

2023-10-05 22:37 UTC, KalynDavis commented on docs/basics/routing.md
>  The different `RedirectType`s are:
@0xTim Oh, My apologies! I was under the impression that this was `type`->`redirectType`. To clarify, it is `redirectType`->`redirect`?

2023-10-05 22:39 UTC, KalynDavis commented on docs/basics/routing.md
>  The different `RedirectType`s are:
Just checked the source code. I see the changes. Thanks!

2023-10-05 22:49 UTC, KalynDavis commented on docs/basics/routing.md
>  The different `RedirectType`s are:
@0xTim I've updated the translations to properly reflect the changes. Thanks for pointing that out!

Note: I did notice that the German translation doesn't look to have the same formatting as the other translations. Gives me the impression the information might be outdated as well.

2023-10-06 05:29 UTC, mattesmohr commented on docs/basics/routing.md
>  The different `RedirectType`s are:
The German translation is fine. 😊. Just different.

2023-10-06 11:56 UTC, 0xTim approved these changes
Thanks!

2023-10-06 12:01 UTC, merged