Recommend Swiftly as install method on Linux
vapor/docs pull request #925
Opened 2023-10-29 22:25 UTC by a40yostudent

Any place we say to install Swift on Linux (deploy docs, getting started etc) should use [Swiftly](https://github.com/swift-server/swiftly/tree/main) instead of directing people to download them from the install pages

2023-10-29 22:27 UTC, gwynne requested changes

2023-10-29 22:27 UTC, gwynne commented on docs/install/linux.md
> +To use Vapor, you will need Swift 5.6 or greater. This can be installed using the CLI tool [Swiftly](https://swift-server.github.io/swiftly/) provided by the Swift Server Workgroup (reccommended), or
We now require 5.7, not 5.6

2023-10-29 22:27 UTC, gwynne commented on docs/deploy/digital-ocean.md
> +Installing Swift 5.8.1
The current latest release is 5.9.1, not 5.8.1

2023-10-29 22:27 UTC, gwynne commented on docs/install/linux.md
> +Installing Swift 5.8.1
5.9.1 again

2023-10-30 06:38 UTC, a40yostudent commented on docs/install/linux.md
> +To use Vapor, you will need Swift 5.6 or greater. This can be installed using the CLI tool [Swiftly](https://swift-server.github.io/swiftly/) provided by the Swift Server Workgroup (reccommended), or
Yes, thank you! I thought I knew that but wasn't able to retrieve this information, can you please point me? I have:
- [x] corrected the Swift version.
- [x]  corrected a typo on this file
- [x] corrected all version on the table about linux, added windows that supports Swift 5.7, as reported on swift.org and Fedora website.

2023-10-30 06:41 UTC, a40yostudent commented on docs/deploy/digital-ocean.md
> +Installing Swift 5.8.1
corrected this, thanks. It was copy pasted from the [Swiftly Github README file](https://github.com/swift-server/swiftly/blob/main/README.md)

2023-11-01 10:57 UTC, a40yostudent commented on docs/basics/routing.it.md
Of course. Should I cancel this PR?

2023-11-01 12:54 UTC, a40yostudent commented on docs/basics/routing.it.md
It should be ok now 👍

2023-11-01 13:27 UTC, 0xTim requested changes
One change around platform support then good to go!

2023-11-01 13:27 UTC, 0xTim commented on docs/install/linux.md
> +|Windows|10|>= 5.7|
We don't support Windows

2023-11-01 13:27 UTC, 0xTim commented on docs/install/linux.md
> +Vapor supports the same versions of Linux distributions that Swift 5.7 or newer versions supports.
I think here we can tweak this to remove the note and table and just link to https://www.swift.org/platform-support/ instead

2023-11-01 14:01 UTC, a40yostudent commented on docs/install/linux.md
> +|Windows|10|>= 5.7|
Oooooops!

2023-11-01 14:09 UTC, a40yostudent commented on docs/install/linux.md
> +Vapor supports the same versions of Linux distributions that Swift 5.7 or newer versions supports.
Well, this information is doomed to be always not up to date, you're right... What about like this?

```md
## Supported Distributions and Versions

Vapor supports the same versions of Linux distributions that Swift 5.7
or newer versions supports. Please refer to the
[official support page](https://www.swift.org/platform-support/)
in order to find updated information about which operating systems
are officially supported.

Linux distributions not officially supported may also run Swift
by compiling the source code, but Vapor cannot prove stability.
Learn more about compiling Swift from
the [Swift repo](https://github.com/apple/swift#getting-started).
```

2023-11-01 15:21 UTC, 0xTim commented on docs/install/linux.md
> +Vapor supports the same versions of Linux distributions that Swift 5.7 or newer versions supports.
Yep that works great

2023-11-01 18:56 UTC, merged