japanese transelation docs\redis\overview.jp.md
vapor/docs pull request #972
Opened 2024-04-19 17:11 UTC by zukizukizuki

## Description 
Japanese translation of redis/overview.md was performed.

## Related Tickets
https://github.com/vapor/docs/issues/911

2024-04-19 17:12 UTC, zukizukizuki commented
@0xTim @KaitoMuraoka
please check it

2024-04-19 21:39 UTC, 0xTim commented
I'll leave this to @gwynne or @KaitoMuraoka to review since my Japanese does not extend past more than a couple of words 😅

2024-06-13 15:31 UTC, lemo-nade-room commented on docs/redis/overview.jp.md
> +# Redis
ファイル名が`overview.ja.md`でないと日本語のWebサイトとして反映されないような気がします。

2024-06-15 04:29 UTC, KaitoMuraoka commented on docs/redis/overview.jp.md
> +# Redis
@lemo-nade-room 
そうですね、

@zukizukizuki 
この場合ファイル名は、Language code を参考にしてください。
日本の場合、[Language code](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) は、`jp` ではなく、`ja` です。
詳細は、[READMEのTranslating](https://github.com/KaitoMuraoka/docs/tree/main?tab=readme-ov-file#translating) をご参照ください。

<details>
<summary>English<\summary>
@lemo-nade-room 
That's right.

@zukizukizuki 
In this case, please refer to the language code for the file name. 
For Japan, [the language code](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) is `ja`, not `jp`.
For more details, please refer to [the Translating section in the README](https://github.com/KaitoMuraoka/docs/tree/main?tab=readme-ov-file#translating).
Thank you.

<\details>

2024-06-15 05:32 UTC, KaitoMuraoka requested changes
Commented.

I am very sorry for the delay in my review. 🙇 
If you still have the passion, please review the suggested changes.
Thank you.

<details><summary>Japaneses</summary>
<p>
コメントしました

レビューが遅くなり大変申し訳ありません 🙇 
もし、あなたにまだ情熱があれば、提案された変更点を見直してください。
よろしくお願いします
</p>
</details>

2024-06-15 05:32 UTC, KaitoMuraoka commented on docs/redis/overview.jp.md
> +Tこのオプションは、最大接続数がどのように維持されるかを決定します。
T isn't needed. 
T が不要

```suggestion
このオプションは、最大接続数がどのように維持されるかを決定します。
```

2024-06-15 05:32 UTC, KaitoMuraoka commented on docs/redis/overview.jp.md
> +任意の`.redis` または[`Application`](https://api.vapor.codes/vapor/documentation/vapor/application) or [`Request`](https://api.vapor.codes/vapor/documentation/vapor/request)インスタンスの .redis プロパティを使用すると[`Redi
I think it's better to translate 'You can send commands' as well. 
While it may be okay to omit it, translating it accurately can help avoid misunderstanding.
<details><summary>Japanese</summary>
<p>
"You can send commands " は翻訳した方が良いと思います。
省略しても良いとは思いますが、正確に翻訳をして行った方が誤解を生まないと思います。
</p>
</details> 

```suggestion
任意の`.redis` または[`Application`](https://api.vapor.codes/vapor/documentation/vapor/application) or [`Request`](https://api.vapor.codes/vapor/documentation/vapor/request)インスタンスの .redis プロパティを使用してコマンドを送信すると、[`RedisClient`](https://swiftpackageindex.com/swift-server/RediStack/main/documentation/redistack/redisclient)にアクセスできます。
```

2024-08-27 10:32 UTC, closed without merging