German translation for Websockets.md #969 #968
vapor/docs pull request #974
Opened 2024-04-25 17:56 UTC by TillTHMAcc

translation-update

2024-04-27 09:15 UTC, mattesmohr commented
@TillTHMAcc Hi, thanks for the contribution. How do you want to do the review? In German or in English?

2024-04-29 11:57 UTC, TillTHMAcc commented
> @TillTHMAcc Hi, thanks for the contribution. How do you want to do the review? In German or in English?

German is good.

2024-05-15 11:22 UTC, ptoffy commented
@mattesmohr any updates on this?

2024-05-15 11:59 UTC, mattesmohr commented
> @mattesmohr any updates on this?

I will do it tonight.

2024-05-15 18:26 UTC, mattesmohr requested changes
Der erste Schwung. @ptoffy Kannst ja mal drüberlesen. Vielleicht war ich zu kritisch. Habe auch ein paar Kommentare dazu geschrieben.

2024-05-15 18:26 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +Zum verbinden eines remote WebSocket endpoint, benutze `WebSocket.connect`.
```suggestion
Um eine solche Verbindung zu einem entfernen WebSocket-Endpunkt herzustellen, benutzen wir `WebSocket.connect`.
```

2024-05-15 18:26 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +### Receiving
Oder lieber `Erhalt von Nachrichten`

2024-05-15 18:26 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +### Sending
```suggestion
### Nachrichtenversand
```

2024-05-15 18:26 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +### Sending
Oder lieber `Versand von Nachrichten`

2024-05-15 18:26 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +## Messages
Oder lieber `Nachrichten`?

2024-05-15 18:26 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +Ping- und Pong-Nachrichten werden vom Client und Server automatisch gesendet, um WebSocket-Verbindungen aufrechtzuerhalten. Deine Anwendung kann mithilfe der Callbacks `onPing` und `onPong` auf diese
```suggestion
Ping- und Pong-Nachrichten werden automatisch vom Client und Server gesendet, um die Verbindung aufrechtzuerhalten. Unsere Anwendung kann mithilfe der Rückruf-Funktionen `onPing` und `onPong` auf diese Ereignisse reagieren.
```

2024-05-16 07:28 UTC, TillTHMAcc commented on docs/advanced/websockets.de.md
> +## Messages
Ich hätte den englischen begriff, gelassen zur besseren Orientierung. Aber wenn du es Deutsch haben möchtest dann würde ich eher Nachrichten oder Nachrichtenverkehr nennen

2024-05-16 07:28 UTC, TillTHMAcc commented on docs/advanced/websockets.de.md
> +### Receiving
Nein Nachrichteneingang hört sich göaube ich treffender an

2024-05-16 07:29 UTC, TillTHMAcc commented on docs/advanced/websockets.de.md
> +### Sending
Vielleicht Senden von Nachrichten

2024-05-20 10:08 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +### Sending
Ich würde es wenn dann mit dem Nachrichteneingang gleich halten.

2024-05-20 10:09 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +## Messages
Ne, ich würde schon lieber übersetzen. Dann finde ich sogar Nachrichtenverkehr besser, da es ja mehr um den Austausch von Nachrichten (Eingang / Ausgang) geht.

2024-05-21 12:48 UTC, TillTHMAcc commented
Ich habe die letzten Sachen berichtigt

2024-06-04 17:40 UTC, mattesmohr approved these changes
The changes look good to me. Github don't let me do any more reviews and I am not sure why. Therefore I approve the PR.

2024-06-04 17:56 UTC, mattesmohr requested changes
These are the last ones. Then, I think, we are good to go.

2024-06-04 17:56 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +Die Methode `connect` gibt einen Future zurück, der abgeschlossen wird, wenn die Verbindung hergestellt ist. Sobald die Verbindung hergestellt ist, wird der bereitgestellte Anschluss mit dem neu verb
```suggestion
Die Methode `connect` gibt einen Future zurück, der abgeschlossen wird, sobald die Verbindung hergestellt ist. Mit Bestehen der Verbindung, wird der bereitgestellte Funktionsabschluss mit dem neu verbundenen WebSocket aufgerufen. Weitere Informationen zur Verwendung dieses WebSockets zum Senden und Lesen von Nachrichten findest du weiter unten.
```

2024-06-04 17:56 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +WebSocket-Handler akzeptieren nicht nur die eingehende HTTP-Request, sondern auch die neu eingerichtete WebSocket-Verbindung. Weitere Informationen zur Verwendung dieses WebSockets zum Senden und Les
```suggestion
WebSocket-Handler akzeptieren neben den eingehenden Anfragen, nun auch die neu eingerichtete WebSocket-Verbindung. Weitere Informationen zur Verwendung dieses WebSockets zum Senden und Lesen von Nachrichten findest du weiter unten.
```

2024-06-04 17:56 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +Der Nachrichtenversand erfolgt asynchron. Du kannst der Sendemethode ein `EventLoopPromise` übergeben, um benachrichtigt zu werden, wenn der Versand der Nachricht abgeschlossen ist oder der Versand f
```suggestion
Der Nachrichtenversand erfolgt asynchron. Du kannst der Sendemethode ein `EventLoopPromise` übergeben, um benachrichtigt zu werden, wenn der Versand der Nachricht abgeschlossen oder fehlgeschlagen ist.
```

2024-06-04 17:56 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +Wenn du `async`/`await` verwendest, wird mit `await` auf den Abschluss des asynchronen Vorgangs zu gewartet
```suggestion
Wenn du `async`/`await` verwendest, wird mit `await` auf den Abschluss des asynchronen Vorgangs gewartet.
```

2024-06-04 17:56 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +Um den WebSocket zu schließen/beenden, rufe die Methode `close` auf.
```suggestion
Um den WebSocket zu schließen, rufe die Methode `close` auf.
```

2024-06-04 17:56 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +Um benachrichtigt zu werden, wenn der Peer die Verbindung schließt, verwende `onClose`. Dieses future wird abgeschlossen, wenn entweder der Client oder der Server den WebSocket schließt.
```suggestion
Um benachrichtigt zu werden, wenn der Peer die Verbindung schließt, verwende `onClose`. Dieses Future wird abgeschlossen, wenn entweder der Client oder der Server den WebSocket schließt.
```

2024-06-04 17:56 UTC, mattesmohr commented on docs/advanced/websockets.de.md
> +Um eine solche Verbindung zu einem entfernen WebSocket-Endpunkt herzustellen, benutzen wir `WebSocket.connect`.
```suggestion
Um eine solche Verbindung zu einem entfernten WebSocket-Endpunkt herzustellen, benutzen wir `WebSocket.connect`.
```

2024-06-05 17:39 UTC, merged