Create middleware.de.md (#751)
vapor/docs pull request #996
Opened 2024-08-03 10:39 UTC by nptr23

translation of the whole document

2024-08-03 10:45 UTC, nptr23 commented
Hey, I wanted to contribute to an open source project for the first time. I chose document out of your list, that needed german translation. I hope i did everything correctly.

2024-08-11 02:12 UTC, 0xTim commented
@nptr23 thanks! I'll let one of the German speakers review it

2024-08-17 09:41 UTC, ptoffy requested changes

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Middleware ist eine Logikkette zwischen dem Client und einem Vapor-Route-Handler. Es ermöglicht Ihnen, Operationen an eingehenden Requests durchzuführen, bevor sie den Route-Handler erreichen, und an
```suggestion
Middleware ist eine Logikkette zwischen dem Client und einem Vapor-Route-Handler. Es ermöglicht dir, Operationen an eingehenden Requests durchzuführen, bevor sie den Route-Handler erreichen, und an ausgehenden Responses, bevor sie zum Client gesendet werden.
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Middleware kann auch zu idividuellen Routen hinzugefügt werden, in dem Route-Gruppen verwedet werden.
```suggestion
Middleware kann auch zu individuellen Routen hinzugefügt werden, in dem Route-Gruppen verwendet werden.
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Die Reihenfolge, in der Middleware hinzugefügt wird, ist wichtig. Requests, die in Ihre Anwendung kommen, durchlaufen die Middleware in der Reihenfolge, in der sie hinzugefügt werden. Responses, die
```suggestion
Die Reihenfolge, in der Middleware hinzugefügt wird, ist wichtig. Requests, die in die Application eingehen, durchlaufen die Middleware in der Reihenfolge in der sie hinzugefügt werden. Responses, die die Application verlassen, gehen in umgekehrter Reihenfolge durch die Middleware zurück. Route-spezifische Middleware wird immer nach der Application-Middleware ausgeführt. Folgendes Beispiel erklärt den Sachverhalt:
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Ein Request an GET /hello wird die Middleware in der folgenden Reihenfolge durchlaufen:
```suggestion
Ein Request an `GET /hello` wird die Middleware in der folgenden Reihenfolge durchlaufen:
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Middleware kann auch _vorangestellt_ werden, was nützlich ist, wenn Sie eine Middleware _vor_ der Standard-Middleware hinzufügen möchten, die Vapor automatisch hinzufügt:
```suggestion
Middleware kann auch _vorangestellt_ werden, was nützlich ist, wenn du eine Middleware _vor_ der Standard-Middleware hinzufügen möchtest, die Vapor automatisch hinzufügt:
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Wenn du async/await verwendest, verwende folgendes Beispiel:
```suggestion
Wenn du `async`/`await` verwendest, verwende folgendes Beispiel:
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Wenn du async/await verwendest, verwende folgendes Beispiel:
```suggestion
Wenn du `async`/`await` verwendest, verwende folgendes Beispiel:
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Sobald FileMiddleware registriert ist, kann eine Datei wie Public/images/logo.png von einer Leaf-Vorlage aus verlinkt werden als <img src="/images/logo.png"/>.
```suggestion
Sobald FileMiddleware registriert ist, kann eine Datei wie `Public/images/logo.png` von einer Leaf-Vorlage aus verlinkt werden als `<img src="/images/logo.png"/>`.
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +// cors middleware should come before default error middleware using `at: .beginning`
```suggestion
// cors-Middleware sollte vor der Standard-Fehler-Middleware mit `at: .beginning` stehen
```

2024-08-17 09:41 UTC, ptoffy commented on docs/advanced/middleware.de.md
> +Da geworfene Fehler sofort an den Client zurückgegeben werden, muss die CORSMiddleware vor der ErrorMiddleware aufgeführt werden. Andernfalls wird die HTTP-Fehlerantwort ohne CORS-Header zurückgegebe
```suggestion
Da geworfene Fehler sofort an den Client zurückgegeben werden, muss die `CORSMiddleware` vor der `ErrorMiddleware` aufgeführt werden. Andernfalls wird die HTTP-Fehlerantwort ohne CORS-Header zurückgegeben und kann nicht vom Browser gelesen werden.
```

2024-08-20 12:30 UTC, ptoffy approved these changes

2024-08-20 12:34 UTC, merged