jwt.de.md german translation for #977
vapor/docs pull request #997
Opened 2024-08-03 11:09 UTC by plse73

2024-08-03 11:13 UTC, plse73 commented
This is my first contribution to the Git community and the processing of open issues. Since I am German and my native language level is German, I hoped to be able to offer added value here. Hopefully I could help and of course I'm looking forward to your feedback. 
Best regards

2024-08-03 11:28 UTC, plse73 commented
Here I have made the translation into German. Unfortunately I could not find the desired label(translation-update) to add it to the request. Clarification would be great here so that I can take it into account in the future.

2024-08-03 14:19 UTC, 0xTim commented
Thanks @plse73 ! I've added the label, it might be you need to scroll to see it or not have permissions yet. I'll leave this for a bit to see if anyone wants to proof read!

2024-08-04 08:48 UTC, ptoffy requested changes
Thanks for this! I have a few nits about using a consistent Anrede in the whole file. Also let's make sure the spacing around titles etc is consistent (e.g leave a space below (sub)titles). Looks good otherwise

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Das JWT-Modul fügt `Application` eine neue Eigenschaft `jwt hinzu, die für die Konfiguration verwendet wird. Um JWTs zu signieren oder zu verifizieren, musst du einen Schlüssel hinzufügen. Der einfac
```suggestion
Das JWT-Modul fügt `Application` eine neue Eigenschaft `jwt` hinzu, die für die Konfiguration verwendet wird. Um JWTs zu signieren oder zu verifizieren, musst du einen Schlüssel hinzufügen. Der einfachste Signieralgorithmus ist HS256 oder HMAC mit SHA-256.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Der `HS256` Unterzeichnern benötigt einen Schlüssel zur Initialisierung. Im Gegensatz zu anderen Unterzeichnern wird dieser eine Schlüssel sowohl zum Signieren _als auch_ zum Verifizieren von Tokens
```suggestion
Der `HS256` Unterzeichner benötigt einen Schlüssel zur Initialisierung. Im Gegensatz zu anderen Unterzeichnern wird dieser eine Schlüssel sowohl zum Signieren _als auch_ zum Verifizieren von Tokens verwendet. Erfahre mehr über die verfügbaren [Algorithmen](#Algorithmen) unten.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Sie können den Inhalt dieses Tokens überprüfen, indem Sie [jwt.io](https://jwt.io) besuchen und das Token in den Debugger einfügen. Setzen Sie den Schlüssel im Abschnitt "Verify Signature" auf `secre
```suggestion
Du kannst den Inhalt dieses Tokens überprüfen, indem du [jwt.io](https://jwt.io) besuchst und das Token in den Debugger einfügst. Setz den Schlüssel im Abschnitt "Verify Signature" auf `secret`.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Weitere Informationen zur Verwendung von JWT mit Vapors Authentifizierungs-API finden Sie unter [Authentifizierung &rarr; JWT](authentication.md#jwt).
```suggestion
Weitere Informationen zur Verwendung von JWT mit Vapors Authentifizierungs-API findest du unter [Authentifizierung &rarr; JWT](authentication.md#jwt).
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Das JWT-Paket von Vapor unterstützt keine RSA-Schlüssel mit einer Größe von weniger als 2048 Bit. Da RSA aus Sicherheitsgründen von der NIST nicht mehr empfohlen wird, sind RSA-Schlüssel hinter einem
```suggestion
!!! warning "Warnung"
    Das JWT-Paket von Vapor unterstützt keine RSA-Schlüssel mit einer Größe von weniger als 2048 Bit. Da RSA aus Sicherheitsgründen von der NIST nicht mehr empfohlen wird, sind RSA-Schlüssel hinter einem `Insecure`-Namensraum eingeschlossen, um von ihrer Verwendung abzuschrecken.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +// Initialisieren Sie einen öffentlichen RSA-Schlüssel mit Komponenten.
```suggestion
// Initialisiere einen öffentlichen RSA-Schlüssel mit Komponenten.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +// Initialisieren Sie einen privaten RSA-Schlüssel mit Komponenten.
```suggestion
// Initialisiere einen privaten RSA-Schlüssel mit Komponenten.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Sie können auch eine PEM-Datei laden:
```suggestion
Du kannst auch eine PEM-Datei laden:
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Verwenden Sie `Insecure.RSA.PrivateKey`, um private RSA-PEM-Schlüssel zu laden. Diese beginnen mit:
```suggestion
Verwende `Insecure.RSA.PrivateKey`, um private RSA-PEM-Schlüssel zu laden. Diese beginnen mit:
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Sobald Sie den RSA-Schlüssel haben, können Sie ihn mit der Methode `addRSA` hinzufügen.
```suggestion
Sobald du den RSA-Schlüssel hast, kannst du ihn mit der Methode `addRSA` hinzufügen.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Sobald Sie den RSA-Schlüssel haben, können Sie ihn mit der Methode `addRSA` hinzufügen.
```suggestion
Sobald du den RSA-Schlüssel hast, kannst du ihn mit der Methode `addRSA` hinzufügen.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Wie bei RSA können Sie ECDSA-Schlüssel über PEM-Dateien laden:
```suggestion
Wie bei RSA kannst du ECDSA-Schlüssel über PEM-Dateien laden:
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +// Initialisieren Sie einen ECDSA-Schlüssel mit öffentlichem PEM.
```suggestion
// Initialisiere einen ECDSA-Schlüssel mit öffentlichem PEM.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Sie können auch einen zufälligen ECDSA-Schlüssel erzeugen, indem Sie den leeren Initialisierer verwenden. Dies ist für Tests nützlich.
```suggestion
Du kannst auch einen zufälligen ECDSA-Schlüssel erzeugen, indem du den leeren Initialisierer verwendest. Dies ist für Tests nützlich.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Sobald Sie den ECDSAKey haben, können Sie ihn mit der Methode `addECDSA` zur Schlüsselsammlung hinzufügen.
```suggestion
Sobald du den ECDSAKey hast, kannst du ihn mit der Methode `addECDSA` zur Schlüsselsammlung hinzufügen.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Wenn Sie mehrere Algorithmen verwenden, können Sie Schlüsselbezeichner (`kid`) verwenden, um sie zu unterscheiden. Wenn Sie einen Algorithmus konfigurieren, übergeben Sie den Parameter "kid".
```suggestion
Wenn du mehrere Algorithmen verwendest, kannst du Schlüsselbezeichner (`kid`) verwenden, um sie zu unterscheiden. Wenn du einen Algorithmus konfigurierst, übergebe den `kid` Parameter.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Wenn Sie JWTs signieren, übergeben Sie den Parameter `kid` für den gewünschten Unterzeichner.
```suggestion
Wenn du JWTs signierst, übergebe den `kid` Parameter für den gewünschten Unterzeichner.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Da [JWKs](#jwk) bereits `kid` Werte enthalten, müssen Sie diese bei der Konfiguration nicht angeben.
```suggestion
Da [JWKs](#jwk) bereits `kid` Werte enthalten, musst du diese bei der Konfiguration nicht angeben.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Alle Ansprüche sollten mit der Methode `JWTPayload.verify` überprüft werden. Wenn der Anspruch eine spezielle verify-Methode hat, können Sie diese verwenden. Andernfalls greifen Sie mit `value` auf d
```suggestion
Alle Ansprüche sollten mit der Methode `JWTPayload.verify` überprüft werden. Wenn der Anspruch eine spezielle verify-Methode hat, kannst du diese verwenden. Andernfalls greife mit `value` auf den Wert des Anspruchs zu und prüfen, ob er gültig ist.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Sie können dann JWTs von Apple an die Methode `verify` übergeben. Der Schlüsselbezeichner (`kid`) im JWT-Header wird verwendet, um automatisch den richtigen Schlüssel für die Verifizierung auszuwähle
This needs updating in the English version too, although we're about to update the docs anyway with v5 coming along so not to worry
```suggestion
Du kannst dieses JSON Web Key Set (JWKS) zu `JWTKeyCollection` hinzufügen.
Du kannst dann JWTs von Apple an die Methode `verify` übergeben. Der Schlüsselbezeichner (`kid`) im JWT-Header wird verwendet, um automatisch den richtigen Schlüssel für die Verifizierung auszuwählen.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +JWT-Herausgeber können ihre JWKS rotieren, was bedeutet, dass Sie gelegentlich einen neuen Download durchführen müssen. Siehe Vapor's unterstützte JWT [Vendors](#vendors) Liste unten für APIs, die di
```suggestion
JWT-Herausgeber können ihre JWKS rotieren, was bedeutet, dass du gelegentlich einen neuen Download durchführen müsst. Siehe Vapor's unterstützte JWT [Vendors](#vendors) Liste unten für APIs, die dies automatisch tun.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Konfigurieren Sie zunächst die Kennung Ihrer Apple-Anwendung.
```suggestion
Konfiguriere zunächst die Kennung deiner Apple-Anwendung.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +// Konfigurieren Sie die Apple-App-Kennung.
```suggestion
// Konfiguriere die Apple-App-Kennung.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Verwenden Sie dann die Hilfsfunktion `req.jwt.apple`, um ein Apple JWT abzurufen und zu überprüfen.
```suggestion
Verwende dann die Hilfsfunktion `req.jwt.apple`, um ein Apple JWT abzurufen und zu überprüfen.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Konfigurieren Sie zunächst Ihre Google-Anwendungskennung und den G Suite-Domänennamen.
```suggestion
Konfiguriere zunächst Ihre Google-Anwendungskennung und den G Suite-Domänennamen.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +// Konfigurieren Sie den Bezeichner der Google-App und den Domänennamen.
```suggestion
// Konfiguriere den Bezeichner der Google-App und den Domänennamen.
```

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Verwenden Sie dann die Hilfe `req.jwt.google`, um ein Google JWT zu holen und zu überprüfen.
As above

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Konfigurieren Sie zunächst die Kennung Ihrer Microsoft-Anwendung.
As above

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +// Konfigurieren Sie die Kennung der Microsoft-App.
As above

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Verwenden Sie dann die Hilfsfunktion `req.jwt.microsoft`, um ein Microsoft JWT abzurufen und zu überprüfen.
As above

2024-08-04 08:48 UTC, ptoffy commented on docs/security/jwt.de.md
> +Das `await` Schlüsselwort ist erforderlich, da die Schlüsselsammlung ein `actor` ist.
```suggestion
!!! tip "Hinweis": 
    Das `await` Schlüsselwort ist erforderlich, da die Schlüsselsammlung ein `actor` ist.
```

2024-08-05 09:56 UTC, plse73 reviewed
Thank you very much for your detailed feedback and comments regarding my mistakes. I hope that I have made the correction in a way that it is now visible. I had a note regarding one of the corrections.

Best regards,

Philip

2024-08-08 06:48 UTC, ptoffy approved these changes

2024-08-10 11:03 UTC, plse73 commented
@ptoffy do I have to do anything else, because the merging is blocked for me. I am not an authorized user for this branch. How do I proceed?

2024-08-11 02:06 UTC, merged